### ISSUE TITLE
Provides a persistent configuration method for the `jenkins-home` directory

### ISSUE THREAD

**Issue by ycyin** [jenkinsci/kubernetes-operator#1056]
**Describe the bug**
By default, the `jenkins-home` directory is mounted using `emptydir`, but if it restarts and crashes, all configuration and plugin directories will be lost.
Why is such a request needed? I installed Jenkins offline and all the plugins were manually copied to the `jenkins-home` directory using `kubectl cp`. If I restart Jenkins, my plugins will be lost and cannot be downloaded (intranet offline status). At the same time, all pipeline configurations are lost.
          
**Additional information**

Kubernetes version: v1.23.3
Jenkins Operator version: v0.8.1

Jenkins-instance.yaml：
```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: default
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.452.3-lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
```
