### ISSUE TITLE
LDAP/AD integration documentation

### ISSUE THREAD

**Issue by bechampion** [jenkinsci/kubernetes-operator#120]
Hey guys.

Is there any documentation around LDAP/AD for the operator , it would be very appreciated.

Thank you

**Comment by bechampion** [comment]
for anyone looking for this
## Custom configuration
Custom configuration can be added in many ways , but the easier one and more elegan is linking configmap references into the CRD definition for example
Create a configmap to be pointed to later on
` kubectl create configmap jenkins-operator-user-configuration-ldap --from-file=ldap.yaml`

ldap.yaml looks like:
```
jenkins:
  securityRealm:
    ldap:
      configurations:
        - groupMembershipStrategy:
            fromUserRecord:
              attributeName: "memberOf"
          inhibitInferRootDN: false
          rootDN: "dc=acme,dc=org"
          server: "ldaps://ldap.acme.org:1636"
```
the above definition is a Configuration As Code definition aka CASC , So to link it the crd looks like:
```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: custom
spec:
  configurationAsCode:
    configurations: 
    - name: jenkins-operator-user-configuration-ldap
  master:
    plugins:
      - name: "ldap"
        version: "1.20"
      - name: "blueocean"
        version: "1.19.0"
    containers:
    ...
```
