### ISSUE TITLE
backups do not seem to be working.

### ISSUE THREAD

**Issue by yoshi314** [jenkinsci/kubernetes-operator#121]
I've setup a simple demo instance, nearly exactly like the docs say - especially the backup sidecar.

However i am not seeing any backup files within the pod, although logs say that backup process executes.

Also, redeploying the pod (without erasing the pvc) makes jenkins restart from scratch (no build history etc). 

Is the backup feature operational, and how can i debug this further?

**Comment by yoshi314** [comment]
Nothing special there, unless i messed up with indentation somewhere.

Does the backup sidecar log anything somewhere?

```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  configurationAsCode:
    configurations: 
    - name: jenkins-operator-user-configuration
  groovyScripts:
    configurations:
    - name: jenkins-operator-user-configuration
  rbac:
    install: true
  master:
    securityContext:
        runAsUser: 1000
        fsGroup: 1000
    JCasC:
      enabled: true
    sidecars:
      configAutoReload:
        enabled: true
    plugins:
      - name: simple-theme-plugin
        version: "0.5.1"
      - name: ldap
        version: "1.20"
      - name: role-strategy
        version: "2.14"
      - name: configuration-as-code-support
        version: "1.19"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
    - name: backup # backup container
      env:
        - name: BACKUP_DIR
          value: /backup
        - name: JENKINS_HOME
          value: /jenkins-home
        - name: BACKUP_COUNT
          value: "3"
      image: virtuslab/jenkins-operator-backup-pvc:v0.0.6
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /jenkins-home
          name: jenkins-home
        - mountPath: /backup
          name: backup
    volumes: 
    - name: backup
      persistentVolumeClaim: 
        claimName: jenkins-backup-example
  backup:
    containerName: backup
    action:
      exec:
        command:
          - /home/user/bin/backup.sh
    interval: 30 # seconds
    makeBackupBeforePodDeletion: true
  restore:
    containerName: backup
    action:
      exec:
        command:
          - /home/user/bin/restore.sh
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
  - id: jenkins-jobs-from-gitlab
    credentialType: basicSSHUserPrivateKey
    credentialID: jenkins-ssh-key
    targets: "cicd/jobs/*.jenkins"
    description: "Gitlab ABS jobs"
    repositoryBranch: master
    repositoryUrl: git@gitlab.local:demo/jenkins-ci-tests.git

```
