### ISSUE TITLE
Role for CRD

### ISSUE THREAD

**Issue by bechampion** [jenkinsci/kubernetes-operator#142]
hey guys is there any way on the CRD definition to change the Role that the service account binds to? 

Not the Role that the operator uses , but the Role that the actual jenkins pod uses (through its service account obvs)

Thank you

**Comment by tomaszsek** [comment]
Hi @bechampion

You can't change it through CR, but you can do it on your own. Let's suppose you have CR `example` in `default` namespace.  
Custom Role:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-role
  namespace: default
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
```
Role binding:
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-role
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-operator-example
roleRef:
  kind: Role
  name: custom-role
  apiGroup: rbac.authorization.k8s.io
```

Cheers
