### ISSUE TITLE
Feature: managing/keeping users database

### ISSUE THREAD

**Issue by pniederlag** [jenkinsci/kubernetes-operator#145]
Is there any advice/best practice or documenation on how to keep the local user database of the jenkins instance? We have our seed-jobs, instances, configuration and secrets in formalized code. backup/restore of job history is working quite fine.

Unfortunatly we have to re-add our users after each time we destroy our jenkins-instance. Would it make sense to add $JENKINS_HOME/users to the backup/restore process?

Thx for any feedback

**Comment by tomaszsek** [comment]
Hi @pniederlag,

The recommend way is to create Kubernetes secret with all users and passwords, than create users through Groovy script or Configuration as Code https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/v0.2.0/customization/.

Kubernetes secret:
```
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: jenkins-conf-secrets
  namespace: default
data:
  user1-name: user1
  user1-pass: secret-user1-pass
```

Groovy:
```
import hudson.security.*

def jenkins = jenkins.model.Jenkins.getInstance()
def hudsonRealm = jenkins.getSecurityRealm()

hudsonRealm.createAccount(secrets["user1-name"], secrets["user1-pass"])

jenkins.save()
```

Configuration as Code:
```
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${user1-name}
          password: ${user1-pass}
```

Cheers
