### ISSUE TITLE
seed-job-agent ServiceAccountName configuration

### ISSUE THREAD

**Issue by bechampion** [jenkinsci/kubernetes-operator#159]
Actually after workin on this a bit , what i think it would make more sense is the builder to run in a different (if configured ServiceAccountName on the Pod Spec) , as then it would be up to the user to bind whatever role to the SA. I'm gonna try to come up with a mini patch this week for you to take a look.

Thank you

**Comment by bechampion** [comment]
Actually after workin on this a bit ,  what i think it would make more sense is the builder to run in a different (if configured ServiceAccountName on the Pod Spec) , as then it would be up to the user to bind whatever role to the SA. I'm gonna try to come up with a mini patch this week for you to take a look.

**Comment by bechampion** [comment]
Here's the PR guys.
https://github.com/jenkinsci/kubernetes-operator/pull/161

Thank you

**Comment by jakalkhalili** [comment]
Hi @bechampion 

Thanks for the PR! We'll check it ASAP

**Comment by tomaszsek** [comment]
Hi @bechampion,

Please take a look at https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml#L359. I thought to add `spec.agent` or `spec.agents` which will cover more use cases.

Cheers

**Comment by bechampion** [comment]
Hi @jakalkhalili @tomaszsek 

Do you mean for `BuilderServiceAccountName`  to be within the `JenkinsSpec{}` struct ?  instead of `Spec.Master{}` as it is right now(in my pr)?

Thank you!

**Comment by bechampion** [comment]
I just understood, I think it's a good idea to lift to the cr definition not only the service account name but all the variables such as image, name, resources etc.
I'll add them to my pr

**Comment by bechampion** [comment]
I've elaborated the idea a bit more , im not so sure about the func getAgentDetails that returns a `map[string]string`  what do you think @jakalkhalili @tomaszsek 
https://github.com/jenkinsci/kubernetes-operator/pull/161/commits/b11573619fe82adf32015c3704301aca0eea83fb

**Comment by bechampion** [comment]
I've moved the userAgentDetails map[string]string to a strcut to go more inline with the code style you follow.

**Comment by pawelprazak** [comment]
We could cover this and a lot more interesting use cases with something like this (as mentioned by @tomaszsek):
```
apiVersion: jenkins.io/v1alpha3
kind: Jenkins    
metadata:    
  name: example    
spec:                                                                                                                                                                                     
  master:
    <custom fields specific for master>
    <k8s-pod-spec>
  agents:
  - <custom fields specific for agents>
    <k8s-pod-spec>
```

Setting the same labels in the Jenkins node and in Kubernetes Pod will allow for better visibility and will enable us to leverage the Jenkin's scheduling and queue management.

At first we'd maintain a static pool of agents/pods (per `spec.agents` entry) and after it's released we could work on custom auto-scaling code in the operator based on information from Jenkins queue and labels.
