### ISSUE TITLE
JENKINS_HOME as a overwrite-able env variable

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#166]
In Openshift, we have the Jenkins home mounted on /var/lib/jenkins 
which can be seen in the 2/Dockerfile.. in the https://github.com/openshift/jenkins repo

It would be really helpful to have JENKINS_HOME env which can be configured through the CR.

**Comment by pawelprazak** [comment]
Have you tried adding `env` section?

Something like:
```
kind: Jenkins
apiVersion: jenkins.io/v1alpha1
metadata:
  ...
spec:
  master:
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        env:
        - name: JENKINS_HOME
          value: /var/lib/jenkins
...
```

There might be other adjustments necessary, but I would give it a try.
