### ISSUE TITLE
Feature Request: Support reference to jenkins-operator creds in user ConfigMap

### ISSUE THREAD

**Issue by tveal** [jenkinsci/kubernetes-operator#19]
I'm trying to pass the jenkins-operator secret (password) to a SecurityRealm plugin via CasC. I see how to do it in the user's config secret, but is there a way to get the operator's credential secret into the user's ConfigMap? The goal is to get the generated operator password into the instantiation of a SecurityRealm plugin as a `roboticSecret`, so that future requests to the Jenkins master can be authenticated in the SecurityRealm plugin. Such as `roboticSecret == operatorPassword` (and user for that matter, but it appears to be hard-coded as `jenkins-operator`). Since the operator cred is re-generated at times, I need the update to the operator's secret to also be refreshed in the user's ConfigMap.

I have to use the Crowd 2 Plugin for Jenkins, but it doesn't support a robotic id as-is, so I'm currently working with a custom local build that adds a robotic id implementation. See the mod [here](https://github.com/tveal/crowd2-plugin/blob/master/docs/robotic-doc.md). I'm also using the **matrix-auth plugin**. Below, the ROBOTIC_ID and ROBOTIC_SECRET need to be the jenkins-operator username and password.

My sample user-config CasC:
```yaml
1-system-config-security.yaml: |2
  jenkins:
    securityRealm:
      crowd:
        applicationName: "${CROWD_APP_NAME}"
        password: "${CROWD_PASSWORD}"
        sessionValidationInterval: 20
        url: "https://path-to-my-crowd-server"
        group: ""
        roboticId: "${ROBOTIC_ID}"
        roboticSecret: "${ROBOTIC_SECRET}"
        roboticGroup: "jenkins-administrators"
2-permisions-matrix.yaml: |2
  jenkins:
    authorizationStrategy:
      globalMatrix:
        permissions:
        - "Agent/Build:jenkins-administrators"
        - "Agent/Configure:jenkins-administrators"
        - "Agent/Connect:jenkins-administrators"
        - "Agent/Create:jenkins-administrators"
        - "Agent/Delete:jenkins-administrators"
        - "Agent/Disconnect:jenkins-administrators"
        ...
```

If I could reference the operator's configuration secret from the user's configmap, then I'd be set. As it is, best I can tell anyways, I can only access the user config secret from the user configmap. That seems reasonable except for this use-case. How can I pass the operator's generated password to the user configmap?

I'd rather not have to do a manual step to copy the creds for the operator secret to the user secret with kubectl - I'd have to run that hack everything the operator regenerates a password and re-instantiate the Jenkins master since it wasn't automated with the operator's management.

**Comment by tomaszsek** [comment]
You can achieve this with:
```
spec:
  master:
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          key: user
          name: jenkins-operator-credentials-<CR-NAME>
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: jenkins-operator-credentials-<CR-NAME>
```
And use `${SECRET_USERNAME}` and `${SECRET_PASSWORD}` in CasC.
