### ISSUE TITLE
Custom Agent pool support [tracking]

### ISSUE THREAD

**Issue by pawelprazak** [jenkinsci/kubernetes-operator#196]
We propose a custom agent pools as a complementary mechanism to Kubernetes plugin of running jobs.
Goals:
- Jenkins native build scheduling (let Jenkins be Jenkins)
- Kubernetes native agent management (let Operator and Kubernetes help with underlying compute)
- generalize the "seed job agent" implementation
- make `kubernetes-plugin` optional :question: (by allowing range to start from 0)

Nongoals:
- reuse or extend any jenkins plugins

Example of how simple manifests could look like:
```yaml
apiVersion: jenkins.io/v1alpha4
kind: Jenkins    
metadata:
  name: example 
spec:                                                                                                                                                                                     
  master:
    <custom fields specific for master>
    <k8s-pod-spec>
  nodes:
  - labelSelector: ...

apiVersion: jenkins.io/v1alpha4
kind: JenkinsNode    
metadata:    
  name: example 
spec:                                                                                                                                                                                     
    <custom fields specific for agents, e.g. no of executors>
    podTemplate: <k8s-pod-template-spec>
```

The **key concept is labels**, both Jenkins labels and Kubernetes labels, this will allow for loose coupling and simplify the solution. 

Setting the same **labels** (synchronizing?) in the Jenkins node and in Kubernetes Pod will allow for better visibility and will enable us to leverage the Jenkin's scheduling, queue management, job node selectors, etc.

At first we'd maintain a static pool of agents/pods (per `spec.agents` entry) and after it's released we could work on custom **auto-scaling** code in the operator based on information from Jenkins queue and labels.

The idea is to have `N` agent types (labeled) with ranges of instances `A..B`.
E.g. a `docker` image builder agent `1...5` instances and a `scala` builder agent `3...9` instances.
Given that we run on Kubernetes anyway, we can overprovision the cluster to **waste less** resources with those agents running all the time compared to a classic "EC2 jenkins agent nodes" scenario.
￼
The autoscaler would look at the Jenkins build queue and the build constraints on the agent labels.
E.g. if we have in queue 3 builds with label `docker` and 15 requiring label `scala`, and, respectively, 1 running, 0 busy, and 5 running and 5 busy, it would scale up the `docker` pool to 2 and `scala` pool to the max 15.

The specific auto-scaling algorithm needs to take into account more things, e.g. mean time of a build of a particular type, or average frequency of jobs of a particular type, but we can start with simple and refine later.

It is actually an extension of what we did for the seed jobs agent,
there is 1 static pod only for running seed jobs to not run those on jenkins master nodes.
 
It's basically the same idea but generalized, in this case 
we have `seed jobs` runner agent with size range `1...1`

---
Related:
- [ ] #228 seed-job-agent resource requests/limits
- ~#159~
- ~#161~
- [ ] #158 Allow to configure no. of seed job executors
- [ ] #239 Tolerations
