### ISSUE TITLE
Feature Request: Add kubernetes-credentials-provider plugin to OperatorPlugins

### ISSUE THREAD

**Issue by blucas** [jenkinsci/kubernetes-operator#2]
The [kubernetes-credentials-provider plugin](https://github.com/jenkinsci/kubernetes-credentials-provider-plugin) would not only be convenient to use for users, but also for the operator itself.  

It could be used to fix [this issue](https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go#L129-L130) with the operator.  Instead of the configure-seed-job having to provided the private key as a build parameter, it could be auto-added to Jenkins using the plugin mentioned.

**Comment by antoniaklja** [comment]
thanks, any examples using this plugin with plain groovy? 

it looks like we would not have to even change the `privateKey` CR section, just change the mechanism of getting private keys from k8s Secret directly for seed job
```
apiVersion: jenkins.io/v1alpha1
kind: Jenkins
metadata:
  name: example
spec:
  master:
   image: jenkins/jenkins:lts
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: git@github.com:jenkinsci/kubernetes-operator.git
    privateKey:
      secretKeyRef:
        name: deploy-keys
        key: jenkins-operator
```

**Comment by blucas** [comment]
The plugin automatically adds k8s secrets to Jenkins internal Credentials store.  So you would use them just as you would use any secret in that store.  Take a look at [this documentation](https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/) for an example.

The way I see it, the `Configure Seed Jobs` would no longer need the `PRIVATE_KEY` param.  Instead it could accept the name of the Jenkins credential that the `Seed job from XXX` would use to authenticate against the seed-job repo.  The `Configure Seed Jobs` would no longer need to create a Jenkins credential as well.

**Comment by tomaszsek** [comment]
Nice tip @blucas 

Operator stores credentials to Jenkins API in Kubernetes secret. Jenkins service account doesn't have permissions to read any secret. This plugin requires list, get and watch permissions for secrets in namespace.

We have to care about security. Ideally would be to prevent run any job on master and kubernetes plugin should spawn agents in separate namespace to prevent mounting secrets from namespace where Jenkins and Operator are running.

**Comment by blucas** [comment]
Thanks for your response @tomaszsek 

I'm not too sure I understand what you are implying.  I think you are saying that Jenkins should **not** be able to access all k8s secrets in the `namespace`.

I don't know if this is a solution to that problem or not, but the `kubernetes-credentials-provider plugin` will only store k8s secrets into Jenkins which have a specific label (`jenkins.io/credentials-type`) assigned to them, without it, the plugin will ignore that secret.
```yaml
---
  labels:
    # The plugin will only create Jenkins Credentials objects 
    # from k8s secrets that contain this label
    "jenkins.io/credentials-type": "usernamePassword"
```
