### ISSUE TITLE
How to upgrade plugin

### ISSUE THREAD

**Issue by zhiyxu** [jenkinsci/kubernetes-operator#22]
Hi

There's a list of base plugins installed by default, but how to upgrade any of those plugins? e.g. if upgrade `kubernetes` plugin in `Jenkins.master.plugins` section as follows:

```
   plugins:
     kubernetes:1.15.5: []
```

Then the operator validation would fail, due to there exists 2 versions for kubernetes plugin.

```
$ kubectl logs jenkins-operator-6d9f5c7ff7-97ngz
...
2019-06-04T02:00:39.985Z        WARN    controller-jenkins      plugins/plugin.go:73    Plugin 'kubernetes:1.15.5' requires version '1.15.5' but plugin 'kubernetes:1.14.8' requires '1.14.8' for plugin 'kubernetes'
2019-06-04T02:00:39.985Z        WARN    controller-jenkins      plugins/plugin.go:73    Plugin 'kubernetes:1.14.8' requires version '1.14.8' but plugin 'kubernetes:1.15.5' requires '1.15.5' for plugin 'kubernetes'
2019-06-04T02:00:39.985Z        WARN    controller-jenkins      jenkins/jenkins_controller.go:154       Validation of base configuration failed, please correct Jenkins CR      {"cr": "example"}
```

So is there any mechanism in jenkins operator for upgrading already installed plugins.

**Comment by tomaszsek** [comment]
Hi @zhiyxu

> $ kubectl logs jenkins-operator-6d9f5c7ff7-97ngz
...
2019-06-04T02:00:39.985Z        WARN    controller-jenkins      plugins/plugin.go:73    Plugin 'kubernetes:1.15.5' requires version '1.15.5' but plugin 'kubernetes:1.14.8' requires '1.14.8' for plugin 'kubernetes'
2019-06-04T02:00:39.985Z        WARN    controller-jenkins      plugins/plugin.go:73    Plugin 'kubernetes:1.14.8' requires version '1.14.8' but plugin 'kubernetes:1.15.5' requires '1.15.5' for plugin 'kubernetes'
2019-06-04T02:00:39.985Z        WARN    controller-jenkins      jenkins/jenkins_controller.go:154       Validation of base configuration failed, please correct Jenkins CR      {"cr": "example"}

I think you have two kubernetes plugins in your CR, one is `1.15.5` and another is `1.14.8`.

> So is there any mechanism in jenkins operator for upgrading already installed plugins.

The operator have build in mechanism for upgrading plugins. If you will modify any plugin and validation will pass the operator will restart Jenkins pod and install new plugins.

Please remember to upgrade all plugins and it's dependencies as well.

**Comment by tveal** [comment]
Howdy @zhiyxu,
I ran into similar problems.
 
> There's a list of base plugins installed by default, but how to upgrade any of those plugins? e.g. if upgrade `kubernetes` plugin in `Jenkins.master.plugins` section as follows:

The keywords here are "base plugins". To upgrade/override those, you need to specify the overrides under `spec.master.basePlugins` instead of `spec.master.plugins` in your CR. Dependencies also matter, so you may or may not get away with the empty array for `kubernetes:1.15.5: []`. I ended up redefining all the basePlugins in my CR with all dependencies, so I wouldn't have to re-figure anything anytime I want to override a base plugin. A bit heavy-handed, but it got the job done.

In my CR, I have all the basePlugins with their dependencies:

```yaml
spec:
  master:
    basePlugins:
      kubernetes:1.15.5:
      - apache-httpcomponents-client-4-api:4.5.5-3.0
      - cloudbees-folder:6.8
      - credentials:2.1.19
      - durable-task:1.29
      - jackson2-api:2.9.9
      - kubernetes-credentials:0.4.0
      - plain-credentials:1.5
      - structs:1.19
      - variant:1.2
      - workflow-step-api:2.19
      workflow-job:2.32:
      - scm-api:2.4.1
      - script-security:1.59
      - structs:1.19
      - workflow-api:2.34
      - workflow-step-api:2.19
      - workflow-support:3.3
      workflow-aggregator:2.6:
      - ace-editor:1.1
      - apache-httpcomponents-client-4-api:4.5.5-3.0
      - authentication-tokens:1.3
      - branch-api:2.5.2
      - cloudbees-folder:6.8
      - credentials-binding:1.18
      - credentials:2.1.19
      - display-url-api:2.3.1
      - docker-commons:1.15
      - docker-workflow:1.18
      - durable-task:1.29
      - git-client:2.7.7
      - git-server:1.7
      - handlebars:1.1.1
      - jackson2-api:2.9.9
      - jquery-detached:1.2.1
      - jsch:0.1.55
      - junit:1.28
      - lockable-resources:2.5
      - mailer:1.23
      - matrix-project:1.14
      - momentjs:1.1.1
      - pipeline-build-step:2.9
      - pipeline-graph-analysis:1.10
      - pipeline-input-step:2.10
      - pipeline-milestone-step:1.3.1
      - pipeline-model-api:1.3.8
      - pipeline-model-declarative-agent:1.1.1
      - pipeline-model-definition:1.3.8
      - pipeline-model-extensions:1.3.8
      - pipeline-rest-api:2.11
      - pipeline-stage-step:2.3
      - pipeline-stage-tags-metadata:1.3.8
      - pipeline-stage-view:2.11
      - plain-credentials:1.5
      - scm-api:2.4.1
      - script-security:1.59
      - ssh-credentials:1.16
      - structs:1.19
      - workflow-api:2.34
      - workflow-basic-steps:2.16
      - workflow-cps-global-lib:2.13
      - workflow-cps:2.69
      - workflow-durable-task-step:2.30
      - workflow-job:2.32
      - workflow-multibranch:2.21
      - workflow-scm-step:2.7
      - workflow-step-api:2.19
      - workflow-support:3.3
      git:3.10.0:
      - apache-httpcomponents-client-4-api:4.5.5-3.0
      - credentials:2.1.19
      - display-url-api:2.3.1
      - git-client:2.7.7
      - jsch:0.1.55
      - junit:1.28
      - mailer:1.23
      - matrix-project:1.14
      - scm-api:2.4.1
      - script-security:1.59
      - ssh-credentials:1.16
      - structs:1.19
      - workflow-api:2.34
      - workflow-scm-step:2.7
      - workflow-step-api:2.19
      job-dsl:1.74:
      - script-security:1.59
      - structs:1.19
      configuration-as-code:1.17:
      - configuration-as-code-support:1.17
      kubernetes-credentials-provider:0.12.1:
      - credentials:2.1.19
      - structs:1.19
      - variant:1.2
```
