### ISSUE TITLE
seed-job-agent resource requests/limits

### ISSUE THREAD

**Issue by CyrilBurd** [jenkinsci/kubernetes-operator#228]
We are running our k8s cluster with ResourceQuota enabled, this means every container should have request/limit for memory/cpu values and this obviously prevents the start of seed-job-agent.

`FailedCreate   replicaset/seed-job-agent-jenkins-temp-79454bd86b   Error creating: pods "seed-job-agent-jenkins-temp-79454bd86b-g5dnr" is forbidden: failed quota: sys: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
`
Is there a way to set the values to **the first** 'seed-job-agent' when jenkins-master starts?
If not, please, consider it as a feature request.
Thanks.

**Comment by pawelprazak** [comment]
As a workaround you can set default s for the namespace like this:
```
kind: LimitRange
apiVersion: v1
metadata:
  name: default-limits
  namespace: jenkins
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    default:
      cpu: 1000m
      memory: 2000Mi
```
