### ISSUE TITLE
Allow to set Tolerations on pods (master & agents)

### ISSUE THREAD

**Issue by pbecotte** [jenkinsci/kubernetes-operator#239]
Need to set tolerations on the jenkins master/agent pods- doesn't seem to be a way to do so?

**Comment by pawelprazak** [comment]
Yes, thank you, this is another thing we need to address with #196

Also the master pod needs to have this configurable.

**Comment by tomaszsek** [comment]
@pbecotte You can set annotations for the Jenkins master pod `spec.master.annotations`.

**Comment by pbecotte** [comment]
Good point, the agent config is in the configuration as code plugin, just hadn't gotten there yet since the master can't deploy :)

**Comment by pbecotte** [comment]
As a question- I still can't figure out any way to work around this. Before I decide to uninstall this operator and get this working with the helm chart, is there a workaround that I'm not seeing?

**Comment by tomaszsek** [comment]
Tolerations for Jenkins master pod can be set in https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.3.1. We have to wait for #196 to set tolerations for seed job agent and I there is no workaround for this :cry:

**Comment by pbecotte** [comment]
That is an impressive turnaround time!

**Comment by tomaszsek** [comment]
In https://github.com/jenkinsci/kubernetes-operator/releases/tag/v0.3.3 the tolerations for seed job agent are copied from `spec.master.tolerations`.

**Comment by deeco** [comment]
How can this be set ? I have tried adding under master 
`master:
       tolerations: [node.kubernetes.io/disk-pressure:NoSchedule]`

**Comment by pbecotte** [comment]
That's not the format for tolerations:

```
                    tolerations:
                      - effect: NoSchedule
                        key: program
                        operator: Equal
                        value: $(PROGRAM)
```

**Comment by deeco** [comment]
> That's not the format for tolerations:
> 
> ```
>                     tolerations:
>                       - effect: NoSchedule
>                         key: program
>                         operator: Equal
>                         value: $(PROGRAM)
> ```

So what would the equivalent be for the above disk-pressure ?

**Comment by deeco** [comment]
believe found it here, https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

`tolerations:
- key: "node.kubernetes.io/unreachable"
  operator: "Exists"
  effect: "NoExecute"
  tolerationSeconds: 6000`

**Comment by deeco** [comment]
works , thanks @pbecotte

**Comment by admssa** [comment]
Does an agent have the same toleration parameter as a master, or tolerations work for master only?

**Comment by pbecotte** [comment]
agent configuration goes in the configuration-as-code configmap.

```
clouds:
  - kubernetes:
      name: kubernetes
      templates:
        - name: default
           tolerations: ...
```
