### ISSUE TITLE
Implement nodeSelectors for the seed job agent.

### ISSUE THREAD

**Issue by salluvada** [jenkinsci/kubernetes-operator#257]
Currently in the Jenkins custom resource manifest, even if I provide a nodeSelector, the generated seed job deployment is not having that. Due to this issue, the seed job agent is stuck in a ContainerCreating state when I am trying this on an EKS cluster with multiple node groups (linux and windows). The **VPC admission webhook** needs the nodeSelector item to be present in the podmanifest without which, it is not adding the label "vpc.amazonaws.com/PrivateIPv4Address" to the pod. 

Error in 
failed to parse Kubernetes args: pod does not have label vpc.amazonaws.com/PrivateIPv4Address

Below is the seed jobs section of the jenkins custom resource manifest. The generated deployment is not having the nodeSelector in it. 
```
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
    nodeSelector:
      beta.kubernetes.io/os: linux
```
