### ISSUE TITLE
User configuration scripts are executed after seed jobs are initialised

### ISSUE THREAD

**Issue by kboom** [jenkinsci/kubernetes-operator#263]
Certain authentication strategies might leverage mounting the secrets, including the GitHub private SSH key, as a volume in the Jenkins master pod. We then need to map those credentials to appropriate global credentials which are then stored and available in Jenkins.

## Example

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-user-configuration
data:
  1-configure-secrets.groovy: |
    import com.cloudbees.jenkins.plugins.sshcredentials.impl.*
    import com.cloudbees.plugins.credentials.*
    import com.cloudbees.plugins.credentials.common.*
    import com.cloudbees.plugins.credentials.domains.Domain
    import com.cloudbees.plugins.credentials.impl.*
    import hudson.util.Secret
    import java.nio.file.Files
    import jenkins.model.Jenkins
    import net.sf.json.JSONObject
    import org.jenkinsci.plugins.plaincredentials.impl.*
    import java.nio.file.Paths


    def jenkins = Jenkins.getInstance()
    def domain = Domain.global()

    jenkins.setSystemMessage('Tesco Identity on Azure')

    def store = jenkins.getExtensionList(SystemCredentialsProvider.class)[0].getStore()
    
    def privateKey = new BasicSSHUserPrivateKey(
      CredentialsScope.GLOBAL,
      "jenkins-git-ssh",
      "<mail>",
      new BasicSSHUserPrivateKey.DirectEntryPrivateKeySource(Secret.fromString(new File('/secrets/jenkins-git-ssh').text),
      '',
      'GIT SSH Private Key'
    )

    // mount GIT credentials from Vault
    store.addCredentials(domain, privateKey)
    
    jenkins.save()
```

And

```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
spec:
  master:
    groovyScripts:
       configurations:
          - name: jenkins-operator-user-configuration
```

And

```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
spec:
  master:
     seedJobs:
       - id: jenkins-operator
         targets: "cicd/jobs/*.jenkins"
         description: "Jenkins Operator repository"
         credentialType: basicSSHUserPrivateKey
         credentialID: jenkins-git-ssh
         repositoryBranch: master
         repositoryUrl: <some GitHub page>
```

This, however, won't work, as the user configuration is applied only after the seed jobs are run, so the credential does not exist yet. Of course we can use Kubernetes secrets to do this job, but it involves some stretching to push the credential there securely.

## Proposal:
I think making the user scripts execute **before** the seed jobs would greatly benefit the elasticity of the solution with no apparent disadvantages or limitations.
