### ISSUE TITLE
Jenkins with SSL termination at ELB - Reverse Proxy issue

### ISSUE THREAD

**Issue by styk-tv** [jenkinsci/kubernetes-operator#277]
Jenkins is a bit unique as to behaviour in reverse proxy. I see service root_url is being populated with the hostname taken from initial setup, however when SSL is terminated at a load balancer things are a bit different. So few questions:

1) What would be a list of recommended annotations either on Ingress http (since https is terminated at ELB).

2) Should the annotations instead of Ingress end up on Service instead? Personal preference is on not touching Service but making all access and hostname decisions in a single place on Ingress type.

3) Single load balancer for all https applications is pointed at all ingress ports so I do not create loadbalancer using ingress definition, hence Ingress nor Service is really aware of ELB.

4) Even if i do end up fixing the headers provided by ELB, jenkins still needs to overwrite its own URL used for redirect. How to overwrite the root service url to fix the reverse proxy messages in config and make sure that all links end up poiting to https instead of default http (obviously programmatically not manually). I was thinking of adding this to ConfigMap with the groovy scripts but maybe you have a better idea.

Script I currently use for other 15 apps has been solid, however Jenkins being more complicated ends up loading correctly on https and then switching back to http on one of the subsequent links of the ui (at random really) and then staying on http.  (because of the above default mapping)

```
apiVersion: networking.k8s.io/v1beta1 
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: jenkins.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: jenkins-operator-http-example
            servicePort: 8080

```
