### ISSUE TITLE
Unable to specify custom plugin location in the jenkins cr

### ISSUE THREAD

**Issue by salluvada** [jenkinsci/kubernetes-operator#296]
Currently, we are only able to specify plugin name and version for downloading plugins. I have come across a situation where I have a couple of plugins that need to be downloaded from a custom url location and not the jenkins UC. 

It would be nice if we can specify some thing like 

```
plugins:
# downloads from the default UC
- name: git
  version: 4.0.0    
# downloads from the user provided url. 
- name: devoptics
  version: 1.2.1
  downloadurl: https://downloadurl/devoptics.hpi   
```
