### ISSUE TITLE
create secrets manually not automatically

### ISSUE THREAD

**Issue by divramod** [jenkinsci/kubernetes-operator#31]
Hey, thx for the awesome project!

I'd like to ask, if it is somehow possible to create the jenkins-operator-credentials-master secret manually, or will it be overwritten by the operator? if its possible to create it manually, should it look like below?
what kind of format does the token need to have? is something missing in the resource below?

thx for hints in advance!

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  user: base64
  password: base64
  token: base64?
```

**Comment by tomaszsek** [comment]
Hi,
> Hey, thx for the awesome project!

I'm glad to hear that.

You can overwrite `user` and `password` in `jenkins-operator-credentials-<cr_name>` secret than restart the Jenkins Pod. Operator won't override it. It will generate new API token to make calls to the Jenkins API. I will be glad if you will update the https://github.com/jenkinsci/kubernetes-operator/blob/master/docs/getting-started.md and add section about it.

Cheers

**Comment by divramod** [comment]
hey, thx for the feedback.

i think i haven't explained correctly, what we like to do.
we want to create all needed resources for jenkins with kubectl / kustomize.

so i created a ```kustomization.yaml``` which looks like that:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
- resources/Namespace.yaml
- resources/Secret.github.yaml
- resources/Secret.jenkins-master.yaml
- resources/CustomResourceDefinition.yaml
- resources/Deployment.yaml
- resources/Role.yaml
- resources/RoleBinding.yaml
- resources/ServiceAccount.yaml
- resources/Jenkins.yaml
- resources/VirtualService.yaml
```
In the resource-files, i collected all the resources you mentioned on the getting started site.

The file ```resources/Secret.jenkins-master.yaml``` looks like that:

```
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-operator-credentials-master
  namespace: jenkins
data:
  user: amVua2lucwo=
  password: cHcK
  token: MTE0ZDgxZWVhZTIyNGJlYTExZWFmMTVjNzEzNWMyNWUyMw==
```

Now my problem is, that when i apply the resources with ```kubectl apply -k .``` the operator fails with the following error code:

![image](https://user-images.githubusercontent.com/1331662/60187023-26001280-982d-11e9-84f9-547670be8a25.png)

So my question is, if it is possible to create the secret in before, together with the other resources. I do not want to overwrite it afterwards.

I am looking forward to improve the documentation (maybe add my example sources and explain a little more in depth, how to setup the pipeline for a private github repository). Thx again for your feedback in advance.

**Comment by tomaszsek** [comment]
> So my question is, if it is possible to create the secret in before, together with the other resources.

Of course you can. It should work with:

```
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-operator-credentials-<cr-name>
  namespace: <namespace>
data:
  user: <base64-encoded-username>
  password: <base64-encoded-password>
```

**Comment by divramod** [comment]
i tried it. when creating the secret together with the other resources as you wrote above, the jenkins operator is not able to generate a api-token and logs the following message (<cr> = master for me):

```
2019-06-27T08:58:07.699Z    WARN    controller-jenkins    jenkins/jenkins_controller.go:159    Reconcile loop failed: couldn't generate API token: parse http://jenkins-operator-http-master:8080/user/jenkins/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken: net/url: invalid control character in URL    {"cr": "master"}
```

if i do not create a secret in before, a secret will be automatically be generated. when inspecting the automatically generated secret you can see, that is has two more data properties: token and tokenCreationTime. i think these are added by the jenkins-<cr> pod.

```
...
data:
  password: Y3A1WkRVY1BlbXRUNzJiWWZ6RU8=
  token: MTExZWU5ZTNmZGI3MWJhYjkwMmJkMWU2N2Q4MjNmZmVmNw==
  tokenCreationTime: MjAxOS0wNi0yN1QwOTowNzo0Mi40Mzg2MzU5MTVa
  user: amVua2lucy1vcGVyYXRvcg==
...
```

if i do create the secret on my own, these two field wont be added.

so the question seems to be how jenkins-<cr> is getting the token and tokenCreationTime into the secret.
