### ISSUE TITLE
Backup stops making backups rather than rotate them after reaching limit

### ISSUE THREAD

**Issue by Nuru** [jenkinsci/kubernetes-operator#360]
# Expected Behavior
When upgrading Jenkins and/or kubernetes-operator, I expect the new Jenkins will be restored from the backups of the previous Jenkins, and backups will continue from there.

# Actual Behavior
After re-deploying Jenkins (as when upgrading), old backups are abandoned in place, and new backups are attempted starting with backup number 1. No restore is done. Old jobs are not deleted until the backup count gets up to the number of the old backup. Until then,
with `BACKUP_COUNT=9`, when it is time for a new backup, `backup` logs:
```
Trimming to only 9 recent backups in preparation for new backup
```
and does not create space for a new backup. 

# Steps to Reproduce the Problem

1. Deploy kubernetes-operator v0.3.3 with chart version 0.1.0 and `backup` Docker image `virtuslab/jenkins-operator-backup-pvc:v0.0.7`, with some configured jobs, and setting 
```yaml
jenkins:
  backup:
    enabled: true
    # interval defines how often make backup in seconds
    interval: 30
    env:
    - name: BACKUP_COUNT
      value: "9" # keep only the 9 most recent backups
    pvc:
      enabled: true
```
2. Run some jobs
2. Wait 30 minutes
3. Upgrade your helm release to kubernetes-operator v0.4.0 with chart version 0.2.0 and `backup` Docker image `virtuslab/jenkins-operator-backup-pvc:v0.0.8` with otherwise same settings.

3. View log output of `backup` and contents of `backup` PersistentVolume.
