### ISSUE TITLE
Error when backup is run

### ISSUE THREAD

**Issue by ekarlso** [jenkinsci/kubernetes-operator#37]
2019-06-25T06:08:28.530Z	INFO	controller-jenkins	backuprestore/backuprestore.go:157	Performing backup '1'	{"cr": "jenkins"}
E0625 06:08:28.758173       1 reflector.go:251] pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/reflector.go:95: Failed to watch *v1.Event: unknown (get events)
2019-06-25T06:08:29.175Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:159	Reconcile loop failed: pod exec error operation on stream: stdout 'Running backup
' stderr 'tar: can't open '/backup/1.tar.gz': Permission denied

```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  backup:
    action:
      exec:
        command:
        - /home/user/bin/backup.sh # this command is invoked on "backup" container to make backup, for example /home/user/bin/backup.sh <backup_number>, <backup_number> is passed by operator
        # - echo
    containerName: backup # container name is responsible for backup
    interval: 30 # how often make backup in seconds
    makeBackupBeforePodDeletion: true # make backup before pod deletion
  master:
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
      - name: backup # container responsible for backup and restore
        env:
        - name: BACKUP_DIR
          value: /backup
        - name: JENKINS_HOME
          value: /jenkins-home
        image: virtuslab/jenkins-operator-backup-pvc:v0.0.2 # look at backup/pvc directory
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /jenkins-home # Jenkins home volume
          name: jenkins-home
        - mountPath: /backup # backup volume
          name: backup
    volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: jenkins-backup-new

    plugins:
      - name: github-branch-source
        version: 2.5.2
      - name: simple-theme-plugin
        version: 0.5.1

  restore:
    action:
      exec:
        command:
        - /home/user/bin/restore.sh # this command is invoked on "backup" container to make restore backup, for example /home/user/bin/restore.sh <backup_number>, <backup_number> is passed by operator
    containerName: backup # container name is responsible for restore backup
    #recoveryOnce: <backup_number> # if want to restore specific backup configure this field and then Jenkins will be restarted and desired backup will be restored
  seedJobs:
  - id: x
    targets: "cicd/jobs/*.jenkins"
    description: "x"
    credentialType: usernamePassword
    credentialID: ghe-x
    repositoryBranch: master
    repositoryUrl: x
```
