### ISSUE TITLE
Error: cannot find volume "jenkins-home" to mount into container "jenkins-master"

### ISSUE THREAD

**Issue by s1apped** [jenkinsci/kubernetes-operator#38]
Hi,

I'm running k8s on azure cloud and tried to setup jenkins-operator with default setup as in documentation using latest version.

I'm getting below error when deploying Jenkins

Error: cannot find volume "jenkins-home" to mount into container "jenkins-master"

![image](https://user-images.githubusercontent.com/32245059/60162124-2e3e5a80-97f9-11e9-9ce6-61f69680e63b.png)

Cheers

**Comment by s1apped** [comment]
I will close it for now as it might me related to azure.

Cheers.

**Comment by tomaszsek** [comment]
Hi @s1apped,

It's strange that k8s have problems with mounting emptyDir volume. Please make sure your k8s nodes have enough free disk space. Could you provide the operator logs?

Cheers

**Comment by s1apped** [comment]
Hi @tomaszsek,

Please see below operator logs

![image](https://user-images.githubusercontent.com/32245059/60212434-88730600-9861-11e9-906a-c237f39a7386.png)

I will double check disk space.

Cheers

**Comment by tomaszsek** [comment]
I think it is different issue. Could you provide logs from command `kubectl -n jenkins get po jenkins-example -o yaml`?

**Comment by s1apped** [comment]
@tomaszsek 

Please see below logs

> apiVersion: v1
> kind: Pod
> metadata:
>   creationTimestamp: "2019-06-27T07:08:37Z"
>   deletionGracePeriodSeconds: 30
>   deletionTimestamp: "2019-06-27T07:09:08Z"
>   labels:
>     app: jenkins-operator
>     jenkins-cr: example
>   name: jenkins-example
>   namespace: jenkins
>   ownerReferences:
>   - apiVersion: jenkins.io/v1alpha2
>     blockOwnerDeletion: true
>     controller: true
>     kind: Jenkins
>     name: example
>     uid: 554757f9-98aa-11e9-9925-62b6192843e3
>   resourceVersion: "6375948"
>   selfLink: /api/v1/namespaces/jenkins/pods/jenkins-example
>   uid: 62335ea5-98aa-11e9-9925-62b6192843e3
> spec:
>   containers:
>   - command:
>     - bash
>     - /var/jenkins/scripts/init.sh
>     env:
>     - name: JENKINS_HOME
>       value: /var/jenkins/home
>     - name: JAVA_OPTS
>       value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
>         -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
>     - name: SECRETS
>       value: /var/jenkins/user-configuration-secrets
>     - name: KUBERNETES_PORT_443_TCP_ADDR
>       value: ci-tools-nitrobox-tools-41de39-892a9c04.hcp.westeurope.azmk8s.io
>     - name: KUBERNETES_PORT
>       value: tcp://ci-tools-nitrobox-tools-41de39-892a9c04.hcp.westeurope.azmk8s.io:443
>     - name: KUBERNETES_PORT_443_TCP
>       value: tcp://ci-tools-nitrobox-tools-41de39-892a9c04.hcp.westeurope.azmk8s.io:443
>     - name: KUBERNETES_SERVICE_HOST
>       value: ci-tools-nitrobox-tools-41de39-892a9c04.hcp.westeurope.azmk8s.io
>     image: jenkins/jenkins:lts
>     imagePullPolicy: Always
>     livenessProbe:
>       failureThreshold: 12
>       httpGet:
>         path: /login
>         port: http
>         scheme: HTTP
>       initialDelaySeconds: 80
>       periodSeconds: 10
>       successThreshold: 1
>       timeoutSeconds: 5
>     name: jenkins-master
>     ports:
>     - containerPort: 8080
>       name: http
>       protocol: TCP
>     - containerPort: 50000
>       name: slavelistener
>       protocol: TCP
>     readinessProbe:
>       failureThreshold: 3
>       httpGet:
>         path: /login
>         port: http
>         scheme: HTTP
>       initialDelaySeconds: 30
>       periodSeconds: 10
>       successThreshold: 1
>       timeoutSeconds: 1
>     resources:
>       limits:
>         cpu: 1500m
>         memory: 3Gi
>       requests:
>         cpu: "1"
>         memory: 500Mi
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>     volumeMounts:
>     - mountPath: /var/jenkins/home
>       name: jenkins-home
>     - mountPath: /var/jenkins/scripts
>       name: scripts
>       readOnly: true
>     - mountPath: /var/jenkins/init-configuration
>       name: init-configuration
>       readOnly: true
>     - mountPath: /var/jenkins/base-configuration
>       name: base-configuration
>       readOnly: true
>     - mountPath: /var/jenkins/user-configuration
>       name: user-configuration
>       readOnly: true
>     - mountPath: /var/jenkins/operator-credentials
>       name: operator-credentials
>       readOnly: true
>     - mountPath: /var/jenkins/user-configuration-secrets
>       name: user-configuration-secrets
>       readOnly: true
>     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       name: jenkins-operator-example-token-l28br
>       readOnly: true
>   dnsPolicy: ClusterFirst
>   nodeName: aks-nodepool1-38729880-1
>   priority: 0
>   restartPolicy: Never
>   schedulerName: default-scheduler
>   securityContext:
>     runAsUser: 1000
>   serviceAccount: jenkins-operator-example
>   serviceAccountName: jenkins-operator-example
>   terminationGracePeriodSeconds: 30
>   tolerations:
>   - effect: NoExecute
>     key: node.kubernetes.io/not-ready
>     operator: Exists
>     tolerationSeconds: 300
>   - effect: NoExecute
>     key: node.kubernetes.io/unreachable
>     operator: Exists
>     tolerationSeconds: 300
>   volumes:
>   - emptyDir: {}
>     name: jenkins-home
>   - configMap:
>       defaultMode: 420
>       name: jenkins-operator-scripts-example
>     name: scripts
>   - configMap:
>       defaultMode: 420
>       name: jenkins-operator-init-configuration-example
>     name: init-configuration
>   - configMap:
>       defaultMode: 420
>       name: jenkins-operator-base-configuration-example
>     name: base-configuration
>   - configMap:
>       defaultMode: 420
>       name: jenkins-operator-user-configuration-example
>     name: user-configuration
>   - name: operator-credentials
>     secret:
>       defaultMode: 420
>       secretName: jenkins-operator-credentials-example
>   - name: user-configuration-secrets
>     secret:
>       defaultMode: 420
>       secretName: jenkins-operator-user-configuration-example
>   - name: jenkins-operator-example-token-l28br
>     secret:
>       defaultMode: 420
>       secretName: jenkins-operator-example-token-l28br
> status:
>   conditions:
>   - lastProbeTime: null
>     lastTransitionTime: "2019-06-27T07:08:37Z"
>     status: "True"
>     type: Initialized
>   - lastProbeTime: null
>     lastTransitionTime: "2019-06-27T07:08:37Z"
>     message: 'containers with unready status: [jenkins-master]'
>     reason: ContainersNotReady
>     status: "False"
>     type: Ready
>   - lastProbeTime: null
>     lastTransitionTime: "2019-06-27T07:08:37Z"
>     message: 'containers with unready status: [jenkins-master]'
>     reason: ContainersNotReady
>     status: "False"
>     type: ContainersReady
>   - lastProbeTime: null
>     lastTransitionTime: "2019-06-27T07:08:37Z"
>     status: "True"
>     type: PodScheduled
>   containerStatuses:
>   - image: jenkins/jenkins:lts
>     imageID: ""
>     lastState: {}
>     name: jenkins-master
>     ready: false
>     restartCount: 0
>     state:
>       terminated:
>         exitCode: 0
>         finishedAt: null
>         startedAt: null
>   hostIP: 10.240.0.5
>   phase: Pending
>   qosClass: Burstable

**Comment by tomaszsek** [comment]
@s1apped As you can see:
```
env:
- name: JENKINS_HOME
  value: /var/jenkins/home
- name: JAVA_OPTS
  value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
-Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
- name: SECRETS
  value: /var/jenkins/user-configuration-secrets
- name: KUBERNETES_PORT_443_TCP_ADDR
 value:
- name: KUBERNETES_PORT
  value: tcp://
- name: KUBERNETES_PORT_443_TCP
  value: tcp://
- name: KUBERNETES_SERVICE_HOST
  value:
```
`JENKINS_HOME`, `JAVA_OPTS` and `SECRETS` is set by the operator but `KUBERNETES_*` is set by AKS itself. The operator detects change in `env` and restart pod over and over again. As workaround you can add `KUBERNETES_*` to CR `spec.master.containers["jenkins-master"].env`.
```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: jenkins
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
    env:
    - name: KUBERNETES_PORT_443_TCP_ADDR
      value:
    - name: KUBERNETES_PORT
      value: tcp://
    - name: KUBERNETES_PORT_443_TCP
      value: tcp://
    - name: KUBERNETES_SERVICE_HOST
      value:
```
The operator should omit `KUBERNTES_*` envs this will be fixed for sure.
