### ISSUE TITLE
Question about kubernetes secret for using seed-jobs

### ISSUE THREAD

**Issue by kaushalringle** [jenkinsci/kubernetes-operator#387]
Reference https://github.com/jenkinsci/kubernetes-operator/issues/79 

How do you guys create a kubernetes_secret in terraform for stringData ?

here is what i have for secret creation which contains git ssh key and username to be used with seed-jobs,

```
resource "kubernetes_secret" "ssh_key" {

  metadata {
    name = "k8s-ssh"
  }

  data = {
    privateKey = "-----BEGIN RSA PRIVATE KEY----- XXXX  -----END RSA PRIVATE KEY-----"
    username =  git-user
  }
}
```

2020-05-13T00:28:25.412Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:310	seedJob `seed-jobs` private key 'privateKey' invalid in secret 'k8s-ssh': failed to decode PEM block

i can see the private key and username are base encoded when retrieved using kubectl get secret k8s-ssh

```
apiVersion: v1
data:
  privateKey: <base64 encoded private key>
  username: <base64 encoded username>
kind: Secret
metadata:
  creationTimestamp: "2020-05-13T00:14:00Z"
  labels:
    app: jenkins-operator
    jenkins-cr: custom-resource
  name: k8s-ssh
  namespace: jenkins
type: Opaque
```

changing data to stringData in kubernetes_secret creation gives a terraform  error. 

```
Error: Unsupported argument

  on main.tf line 23, in resource "kubernetes_secret" "ssh_key":
 23:   stringData = {

An argument named "stringData" is not expected here.
```

- Kubernetes version:

  **Output of kubectl version:**

```
Client Version: v1.15.5
Server Version: v1.14.9-eks-502bfb
```

- Jenkins Operator version:

`base/reconcile.go:554	Jenkins Operator version has changed, actual '' new 'v0.4.0'`
