### ISSUE TITLE
Feature Request:  Support for optional PersistentVolumeClaims

### ISSUE THREAD

**Issue by justyns** [jenkinsci/kubernetes-operator#4]
I would like to see the ability to persist Jenkins' state across pod restarts/moving to another node/etc.  

I think the easiest way to accomplish this would be to mount the jenkins homedir from a persistent volume.  Ideally this would be optional in the CR spec.  An example config might look like this:

``` yaml
---
apiVersion: jenkins.io/v1alpha1
kind: Jenkins
metadata:
  name: example
spec:
  master:
   image: jenkins/jenkins:lts
   persistentHomeVolumeClaim: jenkins-operator-example-pvc
  seedJobs: []
```

If `persistentHomeVolumeClaim` isn't specified, then the current behavior of using an `emptyDir` would still be used.  It could also be `enablePersistence: true` and let the operator generate the pvc, but I'm assuming it should at least be somewhat customizable.

My other thought was that there could be a `customVolumes` key under `spec.master` that would get merged with the final `spec.volumes` in the generated pod resource.  I'm not sure if the added customizability would be needed or not compared to just passing in a claim name.  You'd also probably need `customMounts` to go along with it.
