### ISSUE TITLE
Helm doesn't create Jenkins instance

### ISSUE THREAD

**Issue by peske** [jenkinsci/kubernetes-operator#418]
# Expected Behavior
`helm install` should create Jenkins instance, unless it's disabled in values.
# Actual Behavior
`helm install` doesn't create Jenkins instance.
# Steps to Reproduce the Problem

1. Execute:
```
helm upgrade -i jenkins-operator-release jenkins/jenkins-operator --values jenkins-operator-values.yaml --namespace jenkins
```
(`jenkins-operator-values.yaml` does not contain `enabled: false`. I'll provide the full content below.)
Output:
```
Release "jenkins-operator-release" does not exist. Installing it now.
NAME: jenkins-operator-release
LAST DEPLOYED: Thu Jun 18 02:20:52 2020
NAMESPACE: jenkins
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Watch Jenkins instance being created:
$ kubectl --namespace jenkins get pods -w

2. Get Jenkins credentials:
$ kubectl --namespace jenkins get secret jenkins-operator-credentials-jenkins -o 'jsonpath={.data.user}' | base64 -d
$ kubectl --namespace jenkins get secret jenkins-operator-credentials-jenkins -o 'jsonpath={.data.password}' | base64 -d

3. Connect to Jenkins (actual Kubernetes cluster):
$ kubectl --namespace jenkins port-forward jenkins-jenkins 8080:8080

Now open the browser and enter http://localhost:8080
```

2. Execute:
```
kubectl --namespace jenkins get secret jenkins-operator-credentials-jenkins -o 'jsonpath={.data.user}' | base64 -d
```
No output (empty).

3. Execute:
```
kubectl get all --namespace jenkins
```
Output:
```
NAME                                            READY   STATUS    RESTARTS   AGE
pod/jenkins-operator-release-68c4fcc78f-mlqn2   1/1     Running   0          8m41s

NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/jenkins-operator-metrics   ClusterIP   10.102.140.106   <none>        8383/TCP,8686/TCP   8m38s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jenkins-operator-release   1/1     1            1           8m42s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/jenkins-operator-release-68c4fcc78f   1         1         1       8m42s
```
There's no Jenkins instance.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version:

```
NAME                    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
jenkins-operator-release	jenkins  	1       	2020-06-18 02:20:52.630516391 +0000 UTC	deployed	jenkins-operator-0.3.2	0.4.0 
```

 - Helm version:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

 - `jenkins-operator-values.yaml` file content:

```
---
jenkins:
  # namespace is the namespace where the resources will be deployed
  # It's not recommended to use default namespace
  # Create new namespace for jenkins (called e.g. jenkins)
  namespace: jenkins

  # imagePullSecrets is used if you want to pull images from private repository
  # See https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuration/#pulling-docker-images-from-private-repositories for more info
  imagePullSecrets: []

  # basePlugins are plugins installed and required by the operator
  # Shouldn't contain plugins defined by user
  # You can change their versions here
  # See https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/customization/#install-plugins for more details
  #
  # Example:
  #
  # basePlugins:
  # - name: kubernetes
  #   version: 1.18.3
  # - name: workflow-job
  #   version: "2.34"
  # - name: workflow-aggregator
  #   version: "2.6"
  # - name: git
  #   version: 3.12.0
  # - name: job-dsl
  #   version: "1.76"
  # - name: configuration-as-code
  #   version: "1.29"
  # - name: kubernetes-credentials-provider
  #   version: 0.12.1
  basePlugins:
  - name: kubernetes
    version: "1.26.1"
  - name: workflow-job
    version: "2.39"
  - name: workflow-aggregator
    version: "2.6"
  - name: git
    version: "4.2.2"
  - name: job-dsl
    version: "1.77"
  - name: configuration-as-code
    version: "1.41"
  - name: kubernetes-credentials-provider
    version: "0.15"

  # plugins are plugins required by the user
  # You can define plugins here
  # See https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/customization/#install-plugins for more details
  #
  # Example:
  #
  # plugins:
  # - name: simple-theme-plugin
  #   version: 0.5.1
  plugins:
  - name: credentials-binding
    version: "1.23"
  - name: blueocean
    version: "1.23.2"
  - name: prometheus
    version: "2.0.6"

  # Resource limit/request for Jenkins
  # See https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ for details
  resources:
    limits:
      cpu: 2
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 500Mi

  # volumes used by Jenkins
  # By default, we are only using backup
  volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: jenkins-pvc

  # http Jenkins service
  # See https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/#github.com/jenkinsci/kubernetes-operator/pkg/apis/jenkins/v1alpha2.Service for details
  service:
    type: "NodePort"
    nodePort: 31001
```

**Comment by pniederlag** [comment]
I have seen this also. Can you check wether using `--namespace jenkins` versus don't install with --namespace argument (using "default" namespace) has any effect? For me it worked when I dropped the --namespace argument from helm install.

**Comment by waveywaves** [comment]
@pniederlag That makes sense. 
There needs to be a namespace "jenkins" already present for that.

**Comment by peske** [comment]
@waveywaves `jenkins` namespace with some PVC existed even in my original attempt.

@pniederlag I've tried as you've suggested:
```
helm upgrade -i jenkins-operator-release jenkins/jenkins-operator --values jenkins-operator-values.yaml
```
Output:
```
Release "jenkins-operator-release" does not exist. Installing it now.
NAME: jenkins-operator-release
LAST DEPLOYED: Thu Jun 18 15:55:42 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Watch Jenkins instance being created:
$ kubectl --namespace default get pods -w

2. Get Jenkins credentials:
$ kubectl --namespace default get secret jenkins-operator-credentials-jenkins -o 'jsonpath={.data.user}' | base64 -d
$ kubectl --namespace default get secret jenkins-operator-credentials-jenkins -o 'jsonpath={.data.password}' | base64 -d

3. Connect to Jenkins (actual Kubernetes cluster):
$ kubectl --namespace default port-forward jenkins-jenkins 8080:8080

Now open the browser and enter http://localhost:8080
```

And then:
```
kubectl get all --namespace default
```

Output:
```
NAME                                            READY   STATUS    RESTARTS   AGE
pod/jenkins-operator-release-68c4fcc78f-8hzqf   1/1     Running   0          82s

NAME                               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/jenkins-operator-metrics   ClusterIP   10.111.191.18   <none>        8383/TCP,8686/TCP   79s
service/kubernetes                 ClusterIP   10.96.0.1       <none>        443/TCP             6d18h

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/jenkins-operator-release   1/1     1            1           82s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/jenkins-operator-release-68c4fcc78f   1         1         1       82s
```

Then:
```
kubectl get all --namespace jenkins
```

Output:
```
No resources found in jenkins namespace.
```

So Jenkins instance **isn't installed again**. Note that I do have `jenkins.namespace: jenkins` in the values file (the whole file provided above, in the original description).

**Comment by peske** [comment]
For now I'll go with a workaround: I'll set `jenkins.enable` to `false`, install the operator by using `heml`, and deploy the Jenkins instance later, by creating `Jenkins` resource.

But I hope that you'll find the fix.

@waveywaves It looks much more like `bug` to me than `documentation`.

**Comment by peske** [comment]
I've discovered something interesting. After all the steps I've described in my previous comment (`helm install` without `--namespace jenkins`), althoug there isn't Jenkins instance, it looks that PVC claim is created (or at least attempted to create). Please take a look at the following output:
```
# kubectl get pvc --namespace jenkins
NAME             STATUS    VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS    AGE
jenkins-backup   Pending                                                          9m29s
jenkins-pvc      Bound     jenkins-pv   8Gi        RWO            local-storage   11m
```

There are two PVCs:

1. `jenkins-pvc`, which I created before executing `helm install`, to prepare it for Jenkins instance;
2. `jenkins-backup`, which is created by `helm instanll`, and which is in `pending` state.

So there are now several questions:

1. Why `helm install` attempts to create `jenkins-backup` PVC although I've replaced `jenkins-backup` with `jenkins-pvc` in the values file:
```
  volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: jenkins-pvc
```
2. If the instance cannot be created due to the missing PVC, shouldn't it be created anyway, and be in `pending` state while PVC isn't available? It would be more common behavior, and users would be able to troubleshoot it more efficiently (it's a thing we've accustomed to)?

It definitely looks like a bug.

**Comment by peske** [comment]
I've extracted this PVC problem into a new issue: https://github.com/jenkinsci/kubernetes-operator/issues/422

**Comment by peske** [comment]
Hmmm... Things are getting weirder and weirder here...

I've tried to install the operator only, without Jenkins instance, by creating the following values file (jenkins-operator-values.yaml):
```
---
jenkins:
  enabled: false
```

Then I've executed:
```
helm upgrade -i jenkins-operator-release jenkins/jenkins-operator --values jenkins-operator-values.yaml --namespace jenkins
```
Surprisingly, this command again caused creating `jenkins-backup` PVC, this time in `default` namespace. Questions:
1. Why it creates `jenkins-backup` when `jenkins.enabled` is set to false in the values file?
2. Whi it creates it in `default` namespace although I've specified `--namespace jenkins` with `helm install`? I suppose it's because I haven't specified `jenkins.namespace` in the values file, but again it doesn't make too much sense. Especially that it ignorred `jenkins.enabled` which **is** specified.

But OK, I've deleted `jenkins-backup` PVC manually.

Then I've tried to actually create Jenkins instance by executing:
```
kubectl apply -f jenkins.yaml --namespace jenkins
```
and it kinda executed successfully. Then I've did the following:
```
# kubectl get Jenkins --namespace jenkins
NAME      AGE
jenkins   33m
```
OK, it looks that `Jenkins` resource named `jenkins` is installed. But there's no any pod:
```
# kubectl get pods --namespace jenkins
NAME                                        READY   STATUS    RESTARTS   AGE
jenkins-operator-release-68c4fcc78f-v6z5x   1/1     Running   2          59m
```
Obviously I can't make this thing work. Here's the manifest file I've used for creating `Jenkins` resource:
```
---
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  master:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "2"
          memory: 3Gi
        requests:
          cpu: 500m
          memory: 500Mi
    - name: backup # container responsible for the backup and restore
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "3" # keep only the 2 most recent backups
      image: virtuslab/jenkins-operator-backup-pvc:v0.0.8 # look at backup/pvc directory
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /jenkins-home # Jenkins home volume
        name: jenkins-home
      - mountPath: /backup # backup volume
        name: backup
    service:
      type: "NodePort"
      nodePort: 31001
    volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: jenkins-pvc
    basePlugins:
    - name: kubernetes
      version: "1.26.1"
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.2.2"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.41"
    - name: kubernetes-credentials-provider
      version: "0.15"
    plugins:
    - name: credentials-binding
      version: "1.23"
    - name: blueocean
      version: "1.23.2"
    - name: prometheus
      version: "2.0.6"
    imagePullSecrets:
    - docker-cred
  backup:
    containerName: backup # container name is responsible for backup
    action:
      exec:
        command:
        - /home/user/bin/backup.sh # this command is invoked on "backup" container to make backup, for example /home/user/bin/backup.sh <backup_number>, <backup_number> is passed by operator
    interval: 30 # how often make backup in seconds
    makeBackupBeforePodDeletion: true # make a backup before pod deletion
  restore:
    containerName: backup # container name is responsible for restore backup
    action:
      exec:
        command:
        - /home/user/bin/restore.sh # this command is invoked on "backup" container to make restore backup, for example /home/user/bin/restore.sh <backup_number>, <backup_number> is passed by operator
    #recoveryOnce: <backup_number> # if want to restore specific backup configure this field and then Jenkins will be restarted and desired backup will be restored
  seedJobs:
  - id: twan-infrastructure-jobs
    credentialType: usernamePassword
    credentialID: twan-infrastructure-cred
    targets: "Jenkins/jobs/*.jenkins"
    description: "Jobs defined in twan-infrastructure repository."
    repositoryBranch: master
    repositoryUrl: https://[url-of-my-repo]
```
Note that PVC specified there is `jenkins-pvc`, which exists, as you can see here:
```
# kubectl get pvc --namespace jenkins
NAME          STATUS   VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS    AGE
jenkins-pvc   Bound    jenkins-pv   20Gi       RWO            local-storage   67m
```
Also, some secrets specified in the manifest (`docker-cred` and `twan-infrastructure-cred`) do exist:
```
# kubectl get secret --namespace jenkins
NAME                                             TYPE                                  DATA   AGE
default-token-6gppj                              kubernetes.io/service-account-token   3      69m
docker-cred                                      kubernetes.io/dockerconfigjson        1      52m
jenkins-operator-token-47l4b                     kubernetes.io/service-account-token   3      65m
sh.helm.release.v1.jenkins-operator-release.v1   helm.sh/release.v1                    1      65m
twan-infrastructure-cred                         Opaque                                2      49m
```

It looks that this thing simply **doesn't work**.
