### ISSUE TITLE
Jenkins Operator > Create instance should work on OpenShift

### ISSUE THREAD

**Issue by mnuttall** [jenkinsci/kubernetes-operator#428]
# Expected Behavior

![image](https://user-images.githubusercontent.com/4930573/86115733-3db74a00-bac4-11ea-8e8e-6ec38ae216cc.png)

Pressing 'Create instance' on OpenShift should give a functional, running instance of Jenkins. 

# Actual Behavior

Pressing 'Create instance' opens a yaml editor with the following default content:

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  generation: 1
  name: example
  namespace: jenkins-operator
spec:
  backup:
    action: {}
    containerName: ''
    interval: 0
    makeBackupBeforePodDeletion: false
  configurationAsCode:
    configurations: null
    secret:
      name: ''
  groovyScripts:
    configurations: null
    secret:
      name: ''
  clusterRoles:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
  master:
    basePlugins:
      - name: kubernetes
        version: 1.18.3
      - name: workflow-job
        version: '2.34'
      - name: workflow-aggregator
        version: '2.6'
      - name: git
        version: 3.12.0
      - name: job-dsl
        version: '1.76'
      - name: configuration-as-code
        version: '1.29'
      - name: configuration-as-code-support
        version: '1.19'
      - name: kubernetes-credentials-provider
        version: 0.12.1
    containers:
      - command:
          - /usr/bin/go-init
          - '-main'
          - /usr/libexec/s2i/run
        env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: 'true'
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: 'true'
          - name: DISABLE_ADMINISTRATIVE_MONITORS
            value: 'false'
          - name: KUBERNETES_MASTER
            value: 'https://kubernetes.default:443'
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: 'true'
          - name: JENKINS_SERVICE_NAME
            value: jenkins-operator-http-example
          - name: JNLP_SERVICE_NAME
            value: jenkins-operator-slave-example
          - name: JENKINS_UC_INSECURE
            value: 'false'
          - name: JENKINS_HOME
            value: /var/lib/jenkins
          - name: JAVA_OPTS
            value: >-
              -XX:+UnlockExperimentalVMOptions -XX:+UnlockExperimentalVMOptions
              -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
              -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
        image: 'quay.io/openshift/origin-jenkins:latest'
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 360
          timeoutSeconds: 240
        name: jenkins-master
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 0
          timeoutSeconds: 240
        resources:
          limits:
            cpu: 600m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 3Gi
  restore:
    action: {}
    containerName: ''
  service:
    port: 8080
    type: ClusterIP
  slaveService:
    port: 50000
    type: ClusterIP
```

This yaml is significantly different to that at https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/openshift/. For example it lacks the critical section 

```yaml
serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins-route"}}'
```

Without this, users visiting the default Route are prompted to log in with their OpenShift credentials, but then unable to complete login successfully. 

Neither does the yaml include the section

```yaml
metadata:
  annotations:
    jenkins.io/openshift-mode: 'true'
```

which would seem relevant in this case. 

# Steps to Reproduce the Problem

1. Install the Jenkins operator
2. Click 'create instance'

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```sh
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"4320e48", GitTreeState:"clean", BuildDate:"2020-01-21T19:50:59Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Jenkins Operator version:

```
0.4.1-rc1
  ```

Users should not press 'create instance'. Instead they should visit https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/openshift/. There's no obvious route to this information from the Operator landing page.
