### ISSUE TITLE
Problem with install docker and docker-workflow plugin

### ISSUE THREAD

**Issue by witold-gren** [jenkinsci/kubernetes-operator#445]
# Expected Behavior
After I add docker and docker-workflow plugin to plugins section then operator should just install this plugin an run container.

# Actual Behavior
Current if I use this configuration:
```
    basePlugins:
    - name: kubernetes
      version: "1.26.2"
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.3.0"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.40"
    - name: kubernetes-credentials-provider
      version: "0.15"
    plugins:
    - name: simple-theme-plugin
      version: "0.5.1"
    - name: github-oauth
      version: "0.33"
    - name: matrix-auth
      version: "2.6.2"
    - name: monitoring
      version: "1.83.0"
    - name: aws-credentials
      version: "1.28"
    - name: code-coverage-api
      version: "1.1.6"
    - name: build-with-parameters
      version: "1.4"
    - name: authorize-project
      version: "1.3.0"
    - name: pipeline-utility-steps
      version: "2.6.1"
```
docker and docker-workflow plugin isn't installed. When I add this two plugin use method:
```
    plugins:
    - name: docker
      version: "1.2.0"
    - name: docker-workflow
      version: "1.23"
   ...
```
then container is restarting after readinessProbe check `/login` page.

# Steps to Reproduce the Problem
1. Add plugin docker and docker-workflow which I mentioned above to plugins section,
2. Set jenkins image `jenkins/jenkins:2.235.3-lts`
3. Try run this command

# Additional Info

- Kubernetes version: EKS 1.15.11

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

- Jenkins Operator version:

```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
spec:
  master:
    basePlugins:
    - name: kubernetes
      version: "1.26.2" # 1.26.4
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.3.0"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.40"
    - name: kubernetes-credentials-provider
      version: "0.15"
    plugins:
    - name: simple-theme-plugin
      version: "0.5.1"
    - name: github-oauth
      version: "0.33"
    - name: matrix-auth
      version: "2.6.2"
    - name: monitoring
      version: "1.83.0"
    - name: aws-credentials
      version: "1.28"
    - name: code-coverage-api
      version: "1.1.6"
    - name: build-with-parameters
      version: "1.4"
    - name: authorize-project
      version: "1.3.0"
    - name: pipeline-utility-steps
      version: "2.6.1"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.235.3-lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 180
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 180
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: 1000m
          memory: 1Gi
  seedJobs:
  - id: jenkins-operator
    credentialType: basicSSHUserPrivateKey
    credentialID: jenkins-operator-sshkey
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: git@github.com:XYZ/jenkins.git
  configurationAsCode:
    configurations:
    - name: jenkins-operator-user-configuration
    secret:
      name: jenkins-secrets
  groovyScripts:
    configurations:
    - name: jenkins-operator-user-configuration
    secret:
      name: jenkins-secrets
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-user-configuration
data:
  configuration.yaml: |
    tool:
      git:
        installations:
        - home: "git"
          name: "Default"
    security:
      queueItemAuthenticator:
        authenticators:
        - global:
            strategy: "triggeringUsersAuthorizationStrategy"
    jenkins:
      clouds:
      - kubernetes:
          jenkinsTunnel: "jenkins-operator-slave-jenkins.jenkins.svc.cluster.local:50000"
          jenkinsUrl: "http://jenkins-operator-http-jenkins.jenkins.svc.cluster.local:8080"
          name: "kubernetes"
          namespace: "jenkins"
          retentionTimeout: 15
          serverUrl: "https://kubernetes.default.svc.cluster.local:443"
          templates:
            - name: "jenkins-slave"
              label: "jenkins-slave"
              namespace: "jenkins"
              serviceAccount: "jenkins-deployment"
              imagePullSecrets:
              - name: "dockerhub"
              activeDeadlineSeconds: 28800
              activeDeadlineSecondsStr: "28800"
              showRawYaml: false
              hostNetwork: false
              idleMinutes: 5
              idleMinutesStr: "5"
              nodeSelector: "kubernetes.io/instancegroup=jenkins-slave"
              nodeUsageMode: "NORMAL"
              podRetention: "never"
              annotations:
              - key: "iam.amazonaws.com/role"
                value: "jenkins-node"
              containers:
              - name: "jnlp"
                image: "ORG/jenkins:jnlp-4.3-4-alpine"
                command: "jenkins-slave"
                args: "-url $(JENKINS_URL) -workDir=$(HOME) $(JENKINS_SECRET) $(JENKINS_AGENT_NAME)"
                ttyEnabled: true
                workingDir: "/home/jenkins/agent"
              - name: "docker"
                image: "ORG/jenkins:docker"
                args: "cat"
                command: "/bin/sh -c"
                ttyEnabled: true
                workingDir: "/home/jenkins/agent"
              volumes:
              - hostPathVolume:
                  hostPath: "/var/run/docker.sock"
                  mountPath: "/var/run/docker.sock"
              yaml: |-
                spec:
                  tolerations:
                  - key: dedicated
                    operator: Equal
                    value: jenkins-slave
                    effect: NoSchedule
              yamlMergeStrategy: "override"
              yamls:
              - |-
                spec:
                  tolerations:
                  - key: dedicated
                    operator: Equal
                    value: jenkins-slave
                    effect: NoSchedule
      agentProtocols:
      - "JNLP4-connect"
      - "Ping"
      labelAtoms:
      - name: "monitoring"
      - name: "jenkins-slave"
      - name: "master"
      - name: "seed-job-agent"
      nodes:
      - permanent:
          labelString: "monitoring"
          launcher:
            jnlp:
              workDirSettings:
                disabled: false
                failIfWorkDirIsMissing: false
                internalDir: "remoting"
          mode: EXCLUSIVE
          name: "monitoring"
          retentionStrategy: "always"
      - permanent:
          labelString: "seed-job-agent"
          launcher: "jnlp"
          name: "seed-job-agent"
          nodeDescription: "The jenkins-operator generated agent"
          numExecutors: 5
          remoteFS: "/home/jenkins"
      authorizationStrategy:
        projectMatrix:
          permissions:
          - "Agent/Build:ORGANIZATION*GROUP1"
          - "Agent/Build:ORGANIZATION*GROUP2"
          - "Job/Build:ORGANIZATION*GROUP1"
          - "Job/Build:ORGANIZATION*GROUP2"
          - "Job/Cancel:ORGANIZATION*GROUP1"
          - "Job/Cancel:ORGANIZATION*GROUP2"
          - "Job/Discover:ORGANIZATION*GROUP1"
          - "Job/Read:ORGANIZATION*GROUP1"
          - "Job/Read:ORGANIZATION*GROUP2"
          - "Job/Workspace:ORGANIZATION*GROUP1"
          - "Job/Workspace:ORGANIZATION*GROUP2"
          - "Overall/Administer:witold-gren"
          - "Overall/Read:ORGANIZATION*GROUP1"
          - "Overall/Read:ORGANIZATION*GROUP2"
          - "Run/Delete:ORGANIZATION*GROUP1"
          - "Run/Delete:ORGANIZATION*GROUP2"
          - "Run/Replay:ORGANIZATION*GROUP1"
          - "Run/Replay:ORGANIZATION*GROUP2"
          - "Run/Update:ORGANIZATION*GROUP1"
          - "Run/Update:ORGANIZATION*GROUP2"
          - "SCM/Tag:ORGANIZATION*GROUP1"
          - "SCM/Tag:ORGANIZATION*GROUP2"
          - "View/Read:ORGANIZATION*GROUP1"
          - "View/Read:ORGANIZATION*GROUP2"
      securityRealm:
        github:
          clientID: "24762bc64535096d630d"
          clientSecret: ${jenkins-github-oauth}
          githubApiUri: "https://api.github.com"
          githubWebUri: "https://github.com"
          oauthScopes: "read:org,user:email,repo"
      slaveAgentPort: 50000
    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  scope: GLOBAL
                  id: "github"
                  username: "USERNAME"
                  password: ${github-password}
                  description: "Username/Password Credentials for GitHub"
              - usernamePassword:
                  scope: GLOBAL
                  id: "dockerhub"
                  username: "USERNAME"
                  password: ${dockerhub-password}
                  description: "Username/Password Credentials for DockerHub"
    unclassified:
      simple-theme-plugin:
        elements:
        - cssUrl:
            url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-blue.css"
      buildDiscarders:
        configuredBuildDiscarders:
        - "jobBuildDiscarder"
        - simpleBuildDiscarder:
            discarder:
              logRotator:
                artifactDaysToKeepStr: "14"
                artifactNumToKeepStr: "10"
                daysToKeepStr: "10"
                numToKeepStr: "10"
      gitHubConfiguration:
        apiRateLimitChecker: ThrottleForNormalize
      gitHubPluginConfig:
        configs:
        - name: "GitHub"
        hookUrl: "https://JENKINS_URL/github-webhook/"
      location:
        adminAddress: "devops@COMPANY.io"
        url: "https://JENKINS_URL/"
```

**Comment by witold-gren** [comment]
Does anybody have the same problem when installing these two additional plugins?

**Comment by Sig00rd** [comment]
Tested with Helm installation with v0.5.1 chart and Operator v0.6.0 providing this values.yaml
```
jenkins:
  plugins:
    - name: docker-plugin
      version: "1.2.2"
    - name: docker-workflow
      version: "1.26"
```
When I put docker plugin as ```docker```, Jenkins booted up without plugin section in yaml and with only base plugins installed, so I think the problem was that docker plugin's ID is ```docker-plugin```.
