### ISSUE TITLE
Trying to deploy a jenkins operator and jenkins pod keeps restarting 

### ISSUE THREAD

**Issue by riqtest01** [jenkinsci/kubernetes-operator#451]
# Expected Behavior

# Actual Behavior
Jenkins should be up 
# Steps to Reproduce the Problem

I am following in the installation guide and trying to deploy the jenkins operator. Jenkins pods keeps on terminating and restarting. 

# Additional Info

- Kubernetes version: 1.4

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```
2020-08-25T14:57:29.147Z	INFO	controller-jenkins	base/reconcile.go:105	Some plugins have changed, restarting Jenkins	{"cr": "example"}
2020-08-25T14:57:40.944Z	INFO	controller-jenkins	base/reconcile.go:499	Creating a new Jenkins Master Pod jenkins/jenkins-example	{"cr": "example"}
2020-08-25T14:58:32.016Z	INFO	controller-jenkins	base/reconcile.go:1025	Generating Jenkins API token for operator	{"cr": "example"}
2020-08-25T14:58:32.889Z	WARN	controller-jenkins	base/reconcile.go:217	Missing plugin '{workflow-aggregator 2.6 }'	{"cr": "example"}
2020-08-25T14:58:32.889Z	INFO	controller-jenkins	base/reconcile.go:105	Some plugins have changed, restarting Jenkins	{"cr": "example"}
2020-08-25T14:58:35.369Z	INFO	controller-jenkins	base/reconcile.go:499	Creating a new Jenkins Master Pod jenkins/jenkins-example	{"cr": "example"}
2020-08-25T14:59:18.590Z	INFO	controller-jenkins	base/reconcile.go:1025	Generating Jenkins API token for operator	{"cr": "example"}
2020-08-25T14:59:19.248Z	WARN	controller-jenkins	base/reconcile.go:217	Missing plugin '{workflow-aggregator 2.6 }'	{"cr": "example"}
2020-08-25T14:59:19.248Z	INFO	controller-jenkins	base/reconcile.go:105	Some plugins have changed, restarting Jenkins	{"cr": "example"}
2020-08-25T14:59:30.948Z	INFO	controller-jenkins	base/reconcile.go:499	Creating a new Jenkins Master Pod jenkins/jenkins-example	{"cr": "example"}
2020-08-25T15:00:19.176Z	INFO	controller-jenkins	base/reconcile.go:1025	Generating Jenkins API token for operator	{"cr": "example"}
2020-08-25T15:00:19.967Z	WARN	controller-jenkins	base/reconcile.go:217	Missing plugin '{workflow-aggregator 2.6 }'	{"cr": "example"}
2020-08-25T15:00:19.967Z	INFO	controller-jenkins	base/reconcile.go:105	Some plugins have changed, restarting Jenkins	{"cr": "example"}
2020-08-25T15:00:30.944Z	INFO	controller-jenkins	base/reconcile.go:499	Creating a new Jenkins Master Pod jenkins/jenkins-example	{"cr": "example"}
2020-08-25T15:01:23.109Z	INFO	controller-jenkins	base/reconcile.go:1025	Generating Jenkins API token for operator	{"cr": "example"}
2020-08-25T15:01:23.854Z	WARN	controller-jenkins	base/reconcile.go:217	Missing plugin '{workflow-aggregator 2.6 }'	{"cr": "example"}
2020-08-25T15:01:23.854Z	INFO	controller-jenkins	base/reconcile.go:105	Some plugins have changed, restarting Jenkins	{"cr": "example"}
2020-08-25T15:01:30.948Z	INFO	controller-jenkins	base/reconcile.go:499	Creating a new Jenkins Master Pod jenkins/jenkins-example	{"cr": "example"}
2020-08-25T15:02:22.297Z	INFO	controller-jenkins	base/reconcile.go:1025	Generating Jenkins API token for operator	{"cr": "example"}
2020-08-25T15:02:23.052Z	WARN	controller-jenkins	base/reconcile.go:217	Missing plugin '{workflow-aggregator 2.6 }'	{"cr": "example"}
2020-08-25T15:02:23.052Z	INFO	controller-jenkins	base/reconcile.go:105	Some plugins have changed, restarting Jenkins	{"cr": "example"}
2020-08-25T15:02:25.433Z	INFO	controller-jenkins	base/reconcile.go:499	Creating a new Jenkins Master Pod jenkins/jenkins-example	{"cr": "example"}
2020-08-25T15:03:13.845Z	INFO	controller-jenkins	base/reconcile.go:1025	Generating Jenkins API token for operator	{"cr": "example"}
2020-08-25T15:03:14.566Z	WARN	controller-jenkins	base/reconcile.go:217	Missing plugin '{workflow-aggregator 2.6 }'	{"cr": "example"}
2020-08-25T15:03:14.566Z	INFO	controller-jenkins	base/reconcile.go:105	Some plugins have changed, restarting Jenkins	{"cr": "example"}
2020-08-25T15:03:20.945Z	INFO	controller-jenkins	base/reconcile.go:499	Creating a new Jenkins Master Pod jenkins/jenkins-example	{"cr": "example"}

- Jenkins Operator version:0.40

```
  (paste your output here)
  ```

**Comment by riqtest01** [comment]
`apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git`

**Comment by SylwiaBrant** [comment]
Hello @riqtest01, it's a problem with incompatible plugins. If you upgrade base plugins to newer versions everything should work fine.

**Comment by sraisl** [comment]
> Hello @riqtest01, it's a problem with incompatible plugins. If you upgrade base plugins to newer versions everything should work fine.

Is there any documentation on how to update the base plugins? Putting them into spec.master.basePlugins didn't solve this for me...

**Comment by SylwiaBrant** [comment]
@riqtest01 You did well. In that case please provide logs from Jenkins master, preferably at least 50, the reason is probably stated there.

**Comment by THEjoezack** [comment]
I'm seeing this issue with 0.5, I'm using the jenkins-operator (v0.5.0) chart from https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart

I attached the logs from both the Jenkins and operator pods.

I tried it for both Kubernetes v1.20 and v1.18.17 and had the same effect.  I also tried running with the example jenkins definition from the getting started guide: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/deploy-jenkins/

I am running this on minikube v1.18.1 on Ubuntu on Windows WSL2.

[jenkins.txt](https://github.com/jenkinsci/kubernetes-operator/files/6275258/jenkins.txt)
[operator.txt](https://github.com/jenkinsci/kubernetes-operator/files/6275260/operator.txt)

**Comment by aksakalli** [comment]
I was also getting the same problem from `configuration-as-code` version saying it needs to be `>=1.47`. It was solved when I updated the `jenkins_instance.yaml` with plugin versions.

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    basePlugins:
    - name: kubernetes
      version: "1.29.2"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.5.0"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.47"
    - name: kubernetes-credentials-provider
      version: "0.15"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
```
