### ISSUE TITLE
How to get persistence? is this Backup and Restore?

### ISSUE THREAD

**Issue by Eric-Fontana-Bose** [jenkinsci/kubernetes-operator#452]
# Expected Behavior
When the jenkins pod gets deleted (because a node was drained, or some other reason). I want all my jobs to be
in the same state they were before.

I'm very confused here, is "backup" and "restore" for disaster recovery?   I've used the Helm chart for Jenkins and you just
tell it to use a PVC and all the data is stored there, delete the pod, and all your data is there when using the helm chart.
What am I doing wrong?

# Actual Behavior
After deleting the pod, all jobs are lost.

# Steps to Reproduce the Problem

1. Installed via this yaml

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  generation: 1
  name: example
  namespace: eric-jenkins
spec:
  backup:
    action:
      exec:
        command:
          - /home/user/bin/backup.sh
    interval: 30
    containerName: backup
    makeBackupBeforePodDeletion: true
  configurationAsCode:
    configurations: null
    secret:
      name: ''
  groovyScripts:
    configurations: null
    secret:
      name: ''
  clusterRoles:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
  master:
    basePlugins:
      - name: kubernetes
        version: 1.18.3
      - name: workflow-job
        version: '2.34'
      - name: workflow-aggregator
        version: '2.6'
      - name: git
        version: 3.12.0
      - name: job-dsl
        version: '1.76'
      - name: configuration-as-code
        version: '1.29'
      - name: configuration-as-code-support
        version: '1.19'
      - name: kubernetes-credentials-provider
        version: 0.12.1

    containers:
      - command:
          - /usr/bin/go-init
          - '-main'
          - /usr/libexec/s2i/run
        env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: 'true'
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: 'true'
          - name: DISABLE_ADMINISTRATIVE_MONITORS
            value: 'false'
          - name: KUBERNETES_MASTER
            value: 'https://kubernetes.default:443'
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: 'true'
          - name: JENKINS_SERVICE_NAME
            value: jenkins-operator-http-example
          - name: JNLP_SERVICE_NAME
            value: jenkins-operator-slave-example
          - name: JENKINS_UC_INSECURE
            value: 'false'
          - name: JENKINS_HOME
            value: /var/lib/jenkins
          - name: JAVA_OPTS
            value: >-
              -XX:+UnlockExperimentalVMOptions -XX:+UnlockExperimentalVMOptions
              -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
              -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
        image: 'quay.io/openshift/origin-jenkins:latest'
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 420
          periodSeconds: 360
          timeoutSeconds: 240
        name: jenkins-master
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 0
          timeoutSeconds: 240
        resources:
          limits:
            cpu: 600m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 3Gi
      - name: backup
        env:
          - name: BACKUP_DIR
            value: /backup
          - name: JENKINS_HOME
            value: /jenkins-home
          - name: BACKUP_COUNT
            value: "3" # keep only the 2 most recent backups
        image: virtuslab/jenkins-operator-backup-pvc:v0.0.8 # look at backup/pvc directory
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /jenkins-home # Jenkins home volume
            name: jenkins-home
          - mountPath: /backup # backup volume
            name: backup
    volumes:
      - name: backup # PVC volume where backups will be stored
        persistentVolumeClaim:
          claimName: jenkins-backup

  restore:
    action:
      exec:
        command:
          - /home/user/bin/restore.sh
    containerName: ''
  service:
    port: 8080
    type: ClusterIP
  slaveService:
    port: 50000
    type: ClusterIP
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: >-
        {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins-example"}}

```

Stern output shows that the backups are happening:

```
jenkins-example jenkins-master 2020-08-28 14:44:14 INFO    io.fabric8.jenkins.openshiftsync.BuildWatcher reconcileRunsAndBuilds Reconciling job runs and builds
jenkins-example backup Trimming to only 3 recent backups in preparation for new backup
jenkins-example backup Trimming to only 3 recent backups in preparation for new backup
jenkins-example backup Trimming to only 3 recent backups in preparation for new backup
```

Before deleting the POD, my jenkins looks like this:

![image](https://user-images.githubusercontent.com/28016731/91581128-104c1880-e91c-11ea-96e0-bedcc2f9b4c1.png)

After deleting the pod, everything is gone:

![image](https://user-images.githubusercontent.com/28016731/91581772-e515f900-e91c-11ea-81e4-f99579acaf65.png)

**Comment by vivekmogili-avetta** [comment]
I have this problem too, seems like the restore.sh script run but the files don't load when checking the UI. I even tried manually running restore.sh from this configuration in backup container of the jenkins instance. 

My jenkins-instance.yaml:
```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: avetta
spec:
  master:
    basePlugins:
    - name: kubernetes
      version: "1.25.2"
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.2.2"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.38"
    - name: kubernetes-credentials-provider
      version: "0.13"
    plugins:
    - name: github-oauth
      version: "0.33"
    - name: mailer
      version: "1.32"
    - name: parameterized-trigger
      version: "2.37"
    - name: build-user-vars-plugin
      version: "1.6"
    - name: rebuild
      version: "1.31"
    - name: slack
      version: "2.40"
    - name: build-keeper-plugin
      version: "1.3"
    - name: build-blocker-plugin
      version: "1.7.3"
    - name: build-timeout
      version: "1.20"
    - name: pagerduty
      version: "0.4.1"
    - name: email-ext
      version: "2.73"
    - name: conditional-buildstep
      version: "1.3.6"
    - name: matrix-auth
      version: "2.6.2"
    - name: plugin-usage-plugin
      version: "1.0"
    securityContext:
      runAsUser: 0
      fsGroup: 0
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:2.235.5-lts-alpine
    - name: backup
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "24" # keep only the 2 most recent backups
      image: virtuslab/jenkins-operator-backup-pvc:v0.1.0 # look at backup/pvc directory
      imagePullPolicy: IfNotPresent
```
