### ISSUE TITLE
backups are not executing automatically 

### ISSUE THREAD

**Issue by devopsteam605** [jenkinsci/kubernetes-operator#469]
Hi, I'm using Jenkins operator on Openshift 4.3, and I have added the backup functionality to the Jenkins yaml, as described in the Jenkins documentation:
```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: test
spec:
   backup:
	 action:
       exec:
         command:
           - /home/user/bin/backup.sh 
     containerName: backup 
     interval: 3600
     makeBackupBeforePodDeletion: true 
   master:
	 basePlugins:
	   - name: kubernetes
	     version: 1.18.3
	   <more plugins...>
	 containers:
	   - resources:
	   	   limits:
			 cpu: 900m
			 memory: 6Gi
	   	   requests: 
	   	     cpu: 800m
	   	     memory: 5Gi
	     readinessProbe:
	   	   failureThreshold: 3
	       <more non relevant filed..> 	
	     name: jenkins-master
	     image: jenkins/jenkins:lts
	     env:
	     <......>
	   - resources:
	   	   limits:
	   	     cpu: 500m
	   	     memory: 3Gi
	   	   requests: 
	   	     cpu: 400m
	   	     memory: 2Gi
	     name: backup
	     command:
		   - sleep
		   - infinity
	     env:
	       - name: BACKUP_PATH
	   	     value: /backup
	       - name: JENKINS_HOME
	   	     value: /var/lib/jenkins
	     securityContext:
	   	   capabilities:
	   	     drop:
	   		   - KILL
	   		   - MKNOD
	   		   - SETGID
	   		   - SETUID
	   	   runAsUser: 1000
	     imagePullPolicy: Always
	     volumeMounts:
	   	   - mountPath: /var/lib/jenkins
	   	     name: jenkins-home
	   	   - mountPath: /home/user/bin/backup.sh
	   	     name: backup-scripts
	   	     subPath: backup.sh
	   	     readOnly: true
	   	   - mountPath: /home/user/bin/restore.sh
	   	     name: backup-scripts
	   	     subPath: restore.sh
	   	     readOnly: true
	   	   - mountPath: /backup
	   	     name: backup-dir
	     image: quay.io/virtuslab/aws-cli:1.16.263-2
	     workingDir: /home/user/bin/
	 disableCSRFProtection: false
     securityContext:
        fsGroup: 1000
        seLinuxOptions:
           level: 's0:c24,c14'
     volumes:
	   - name: backup-scripts
         configMap:
         defaultMode: 0754
         name: jenkins-operator-backup-s3
	   - name: backup-dir 
	     persistentVolumeClaim:
		   claimName: test
   restore:
     containerName: backup 
     action:
       exec:
         command:
           - /home/user/bin/restore.sh
    <...>
```

When I execute the scripts manually from the backup container, they work fine, but the backup script doesn't run automatically every 3600 seconds as set on the yaml.

Is there anything I'm missing?
Thanks in advance!
