### ISSUE TITLE
Seed job custom image

### ISSUE THREAD

**Issue by andrewkaczynski** [jenkinsci/kubernetes-operator#471]
Hello Guys, I ran Jenkins operator in the environment with no access to public images. Its restricted solely to private repositories. Everything works quite good despite the fact that seed job is using public image. Are there a plans to move it as custom option to CRD? It would solve my issue...

https://github.com/jenkinsci/kubernetes-operator/blob/824ff15dc0f7a7e76476d50892632825d362e06f/pkg/configuration/user/seedjobs/seedjobs.go#L428

Regards, Andrzej

**Comment by Fixmetal** [comment]
related to #470

**Comment by SylwiaBrant** [comment]
Hello, as part of our [Roadmap](https://github.com/jenkinsci/kubernetes-operator/blob/master/ROADMAP.md) we're working on features that will enable using custom seed job image. Please look forward to it :)

**Comment by marcportabellaclotet-mt** [comment]
I have the same issue.
Meanwhile, I solved it by using mutation webhooks, which are awesome.
Have a look at kyverno.
https://kyverno.io/policies/other/replace_image_registry/replace_image_registry/

**Comment by kkujala** [comment]
It can be changed with
```yaml
env:
- name: JAVA_TOOL_OPTIONS
  value: "-Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage=my.registry.example/jenkins/inbound-agent:4.11-1-jdk11"
```

In case registry credentials are needed then this is needed in the pod template
```yaml
imagePullSecrets:
- name: my-registry-example-k8s-secret
imagePullPolicy: Always
```
