### ISSUE TITLE
jenkins operator backup does not restore any jobs, or org folders, or job folders at all.

### ISSUE THREAD

**Issue by agnewp** [jenkinsci/kubernetes-operator#481]
# Expected Behavior
I can see my pipelines and jobs after the jenkins pod is destroyed and created

# Actual Behavior
I get a view in the UI of absolutely no jobs or pipelines

# Steps to Reproduce the Problem

1. fresh working jenkins instance
2. add a pipeline from my github enterprise org 
3. observe at least one successful backup log message in operator
3. delete the jenkins pod
4. wait for successful restore log message in operator
5. restart jenkins for good measure. maybe even hit the reload config from disk button
6. observe no pipeline present in my very empty looking jenkins instance

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-13T19:50:45Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  
```

- Jenkins Operator version:

```
0.4.0
  ```

so i see that in your backup script, you exclude config.xml inside of job subfolders. i completely don't understand why you all did this or how you expect restore to work without the configuration of the jobs, jobs folders, organization folders, pipelines etc. i am working on an alternate solution in the mean time using thin backup.

- jenkins CR:

```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: x-ash-a-12-team-jenkins
spec:
  configurationAsCode:
    configurations: 
    - name: jenkins-operator-user-configuration
    secret:
      name: jenkins-conf-secrets
  groovyScripts:
    configurations:
    - name: jenkins-operator-user-configuration
    secret:
      name: jenkins-conf-secrets
  master:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    basePlugins:
    - name: kubernetes
      version: "1.28.4"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.4.5"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.40" # anything 1.41 and higher is currently not compatible with jenkins operator
    - name: kubernetes-credentials-provider
      version: "0.15"

    plugins:
    - name: github-api
      version: "1.117"
    - name: github-oauth
      version: "0.33"
    - name: Office-365-Connector
      version: "4.13.2"
    - name: blueocean
      version: "1.24.3"
    - name: simple-theme-plugin
      version: "0.6"
    - name: pipeline-utility-steps
      version: "2.6.1"
    - name: http_request
      version: "1.8.27"
    - name: parameterized-scheduler
      version: "0.9"
    - name: code-coverage-api
      version: "1.2.0"
    - name: cobertura
      version: "1.16"
    - name: embeddable-build-status
      version: "2.0.3"
    - name: github-pr-coverage-status
      version: "2.1.1"
    - name: basic-branch-build-strategies
      version: "1.3.2"
    - name: authorize-project
      version: "1.3.0"

    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      env:
      - name: SECRETS_FILE
        value: /var/jenkins/configuration-as-code-secrets
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
      volumeMounts:
       - mountPath: /backup # backup volume
         name: backup
    - name: backup
      env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: "9" # keep only the 9 most recent backups
      image: virtuslab/jenkins-operator-backup-pvc:v0.1.0 # look at backup/pvc directory
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /jenkins-home # Jenkins home volume
        name: jenkins-home
      - mountPath: /backup # backup volume
        name: backup
    volumes:
    - name: backup # PVC volume where backups will be stored
      persistentVolumeClaim:
        claimName: jenkins-backup

  backup:
    containerName: backup # container name is responsible for backup
    action:
      exec:
        command:
        - /home/user/bin/backup.sh # this command is invoked on "backup" container to make backup, for example /home/user/bin/backup.sh <backup_number>, <backup_number> is passed by operator
    interval: 30 # how often make backup in seconds
    makeBackupBeforePodDeletion: true # make a backup before pod deletion
  restore:
    containerName: backup # container name is responsible for restore backup
    action:
      exec:
        command:
        - /home/user/bin/restore.sh # this command is invoked on "backup" container to make restore backup, for example /home/user/bin/restore.sh <backup_number>, <backup_number> is passed by operator
    #recoveryOnce: 8 # if want to restore specific backup configure this field and then Jenkins will be restarted and desired backup will be restored
```
