### ISSUE TITLE
Unable to get Credentials tab for verification of seed job configuration

### ISSUE THREAD

**Issue by RitushreePurkait96** [jenkinsci/kubernetes-operator#485]
# Expected Behavior

According to the official documentation https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuration/ ,
Jenkins Operator will automatically discover and configure all the seed jobs, which can be verified from the " Credentials " tab.

# Actual Behavior
No "Credentials" tab appears and targets not found, though `seedJobs` is specified in the jenkins instance.

# Steps to Reproduce the Problem

1.Install the operator from Operatorhub.io
```execute
kubectl create -f https://operatorhub.io/install/jenkins-operator.yaml
```
2.used `jenkins_instance.yaml` as below:
```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
```
create instance:
```execute
kubectl create -f jenkins_instance.yaml -n my-jenkins-operator
```
3.Getting login credentials:
```
kubectl -n my-jenkins-operator get secret jenkins-operator-credentials-example -o 'jsonpath={.data.user}' | base64 -d
kubectl -n my-jenkins-operator get secret jenkins-operator-credentials-example -o 'jsonpath={.data.password}' | base64 -d
```
4.Creating nodeport patch for the service:
```
kubectl get service jenkins-operator-http-example --output yaml -n my-jenkins-operator > /tmp/my-jenkins.yaml
sed -i "s/type: .*/type: NodePort/g" /tmp/my-jenkins.yaml
kubectl patch svc jenkins-operator-http-example -p "$(cat /tmp/my-jenkins.yaml)" --namespace my-jenkins-operator
kubectl get service jenkins-operator-http-example --output yaml -n my-jenkins-operator > /tmp/my-jenkins.yaml
sed -i "s/nodePort: .*/nodePort: 32379/g" /tmp/my-jenkins.yaml
kubectl patch svc jenkins-operator-http-example -p "$(cat /tmp/my-jenkins.yaml)" --namespace my-jenkins-operator
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
 ```
 Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

- Jenkins Operator version:

```
0.3.0 (Current operator version in https://operatorhub.io/operator/jenkins-operator)
```
It would be great to know if any of the above steps are done in a wrong way or what to do to get the seed jobs in the jenkins console. Thanks in advance.

**Comment by SylwiaBrant** [comment]
Hello, was there anything suspicious in the logs? Could you provide logs from the operator? Maybe events?

**Comment by majinghe** [comment]
Hi @RitushreePurkait96 , please try to add the `credentialID` and `credentialType` in the seedJobs spec, for example
```
  seedJobs:
  - id: jenkins-operator
    credentialType: basicSSHUserPrivateKey
    credentialID:  your-ssh-private-key
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
```

But first make sure the credentials `your-ssh-private-key` already exists on the jenkins. This  works fine for me.
