### ISSUE TITLE
Cannot create master pod because Configuration as Code plugin is too old (Need 1.47)

### ISSUE THREAD

**Issue by AaronJaegerVA** [jenkinsci/kubernetes-operator#523]
**Describe the bug**
Cannot create master pod because Configuration as Code plugin is too old (Need 1.47)

**To Reproduce**
`k create jenkins -f jenkins-master.yaml` # with no basePlugins: specified

Get error like:
```
 - Failed to load: Credentials Plugin (2.3.15)
 - Need Configuration as Code (1.46) >= 1.47
```

I added:

```
    basePlugins:
    - name: kubernetes
      version: "1.28.6"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.5.0"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.47"
    - name: kubernetes-credentials-provider
      version: "0.15"
```

And things are working, finally.
