### ISSUE TITLE
LDAP configure error using operator

### ISSUE THREAD

**Issue by majinghe** [jenkinsci/kubernetes-operator#537]
Dear team

when i try to use operator to install jenkins ldap plugin, below is my configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
data:
  jenkins-ldap-cm.yaml: |
    jenkins:
      systemMessage: "LDAP configured"
      securityRealm:
        ldap:
          configurations:
            - server: "ldaps://xxxxxxx:636"
              rootDN: "xxxxx"
              userSearchBase: "xxxxx"
              userSearch: "mail={0}"
              groupSearchBase: "xxxxxxxx"
              groupMembershipStrategy:
                fromGroupSearch:
                   filter: ""
              managerDN: ""
              managerPasswordSecret: ""
              displayNameAttributeName: "displayname"
              mailAddressAttributeName: "mail"
              ignoreIfUnavailable: "false"
              inhibitInferRootDN: "false"
```
but the operator shows
```
Name 'jenkins-ldap-cm.yaml' groovy script execution failed, logs :
java.lang.IllegalArgumentException: No hudson.security.SecurityRealm implementation found for ldap
```
ldap should have the class `hudson.security.LDAPSecurityRealm` instead of `hudson.security.SecurityRealm `, how to fix this?
