### ISSUE TITLE
Helm installation will not create default Jenkins instance if operator is in different namespace

### ISSUE THREAD

**Issue by r0bnet** [jenkinsci/kubernetes-operator#541]
**Describe the bug**
When following the documentation and installing the operator e.g. in the `jenkins` namespace then it will start to watch exactly this namespace:

```yaml
...
env:
- name: WATCH_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
...
```

If you leave now a default Jenkins instance then it will be deployed in the `default` namespace which means that it will not be created since the operator watches `jenkins`.

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: default
...
```

All the information above is taken from the rendered chart itself (even when using `-n jenkins`).

Two approaches to fix it:
- Watch all namespaces (probably not)
- fix the namespace of the Jenkins instance in the chart to use the same one as the operator.

I guess the problem is that the template for the Jenkins instances sources the namespace from a specific value `jenkins.namespace` but not sure if that's the correct way.

```yaml
# namespace is the namespace where the resources will be deployed
# It's not recommended to use default namespace
# Create new namespace for jenkins (called e.g. jenkins)
namespace: default
```

Kubernetes version: 1.20.4
Jenkins Operator version: 
- Chart: 0.4.3
- Operator: 0.5.0
