### ISSUE TITLE
 Unrecognized VM option 'UseCGroupMemoryLimitForHeap' during installation 

### ISSUE THREAD

**Issue by koromkorom** [jenkinsci/kubernetes-operator#554]
**Describe the bug**
jenkins master wont start. Stays in Pending 

**To Reproduce**
I used thos two yamls: 
https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/crds/jenkins_v1alpha2_jenkins_crd.yaml
https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/all-in-one-v1alpha2.yaml

**Additional information**
Kubernetes version: 1.16.15-gke.14800
Jenkins Operator version: 0.5.0

**Logs**
I got this from kubectl logs -f -n jenkins jenkins-example

Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by prryb** [comment]
Hey, @koromkorom - could you provide the yaml for your Jenkins instance? The two yaml files you mentioned will install the CRD and the operator, and that works.

On a side note: `UseCGroupMemoryLimitForHeap` VM option has been removed in JDK 11 (and replaced with `UseContainerSupport`) - you may be using jdk11 Jenkins image. 

`UseContainerSupport` has been backported into jdk 8u191 and is on by default. If your image uses jdk that has that on, it's safe to remove `UseCGroupMemoryLimitForHeap` from `JAVA_OPTS` env var on the container.

**Comment by koromkorom** [comment]
Hey, @prryb 

Yes I read that this option has been removed. But the only source of setting that option has to be the operator. 

I got the Jenkins Instance yaml from here: https://www.jenkins.io/doc/book/installing/kubernetes/#deploy-jenkins-2

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  master:
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts-jdk11
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
```
