### ISSUE TITLE
Generated credentials overridden if creating additional credentials in CasC

### ISSUE THREAD

**Issue by leifmadsen** [jenkinsci/kubernetes-operator#557]
**Describe the bug**

When creating additional credentials with CasC and loading it via the `configurations` parameter in a `Jenkins` object, the generated credentials are overridden.

**To Reproduce**

First, create a regular `Jenkins` object without any additional configuration. Browse the web UI and go to the Credentials section. Note that a UUID credential has been created. (This is using the Jenkins image on OpenShift using the `serviceAccount` authorization strategy, in case this matters).

Jenkins object:

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
...
spec:
  jenkinsAPISettings:
    authorizationStrategy: serviceAccount
  master:
    basePlugins:
    - name: kubernetes
      version: 1.29.0
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: 4.5.2
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.47"
    - name: kubernetes-credentials-provider
      version: "0.15"
    containers:
    - command:
      - /usr/bin/go-init
      - -main
      - /usr/libexec/s2i/run
      env:
      - name: OPENSHIFT_ENABLE_OAUTH
        value: "true"
      - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
        value: "true"
      - name: INSTALL_PLUGINS
        value: kubernetes-credentials-provider:0.15,config-file-provider:3.7.1,github-branch-source:2.10.2
      - name: DISABLE_ADMINISTRATIVE_MONITORS
        value: "false"
      - name: KUBERNETES_MASTER
        value: https://kubernetes.default:443
      - name: KUBERNETES_TRUST_CERTIFICATES
        value: "true"
      - name: JENKINS_SERVICE_NAME
        value: jenkins-operator-http-cloudops
      - name: JNLP_SERVICE_NAME
        value: jenkins-operator-slave-cloudops
      - name: JENKINS_UC_INSECURE
        value: "false"
      - name: JENKINS_HOME
        value: /var/lib/jenkins
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true
      image: quay.io/openshift/origin-jenkins:latest
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: jenkins-master
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1000570000
    disableCSRFProtection: true
    securityContext:
      fsGroup: 1000570000
      seLinuxOptions:
        level: s0:c24,c9
  restore:
    action: {}
    containerName: ""
    getLatestAction: {}
  roles:
  - apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  service:
    port: 8080
    type: ClusterIP
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins-cloudops"}}'
  slaveService:
    port: 50000
    type: ClusterIP
```

Create a ConfigMap with a CasC configuration like so:

```yaml
apiVersion: v1
data:
  1-gh-app-credentials.yaml: |
    credentials:
      system:
        domainCredentials:
        - credentials:
          - gitHubApp:
              appID: "12345678"
              description: "GitHub app"
              id: "github-app"
              privateKey: "${GITHUB_APP_KEY}"
kind: ConfigMap
```

Create the corresponding `Secret` to load as the `GITHUB_APP_KEY` in the `ConfigMap`:

```yaml
apiVersion: v1
data:
  GITHUB_APP_KEY: LS0tLS1CRU...LS0tLS0K
kind: Secret
```

Load the configuration in to the `Jenkins` object:

```yaml
...
Kind: Jenkins
...
spec:
...
  configurationAsCode:
    configurations:
    - name: jenkins-operator-github-credentials
    secret:
      name: github-app-key
...
```

**Additional information**

You can work around the issue by defining the following additional configuration in CasC:

```yaml
          - fileSystemServiceAccountCredential:
              id: "1a12dfa4-7fc5-47a7-aa17-cc56572a41c7"
              scope: GLOBAL
```

Such as:

```yaml
apiVersion: v1
data:
  1-gh-app-credentials.yaml: |
    credentials:
      system:
        domainCredentials:
        - credentials:
          - fileSystemServiceAccountCredential:
              id: "1a12dfa4-7fc5-47a7-aa17-cc56572a41c7"
              scope: GLOBAL
          - gitHubApp:
              appID: "12345678"
              description: "GitHub app"
              id: "github-app"
              privateKey: "${GITHUB_APP_KEY}"
kind: ConfigMap
```

Kubernetes version: 1.18.3 (OpenShift 4.5.38)
Jenkins Operator version: 0.5.0
