### ISSUE TITLE
envFrom does not propagate to master

### ISSUE THREAD

**Issue by rosscdh** [jenkinsci/kubernetes-operator#560]
**Describe the solution you'd like**
envFrom should propagate to the master pod so that env vars can be used in JSasC setups

**Describe alternatives you've considered**
when JSasC runs it needs access to env vars that may contain secrets (and thus come from secrets of configmaps) envFrom is supported on the Jenkins scheme but do not propagate tot eh generated master pod.

ie.. instead of

```
            - gitLabApiTokenImpl:
                scope: GLOBAL
                id: gitlab-cloud-token
                apiToken: "xxxxXXXXXXXX"
                description: "Gitlab Cloud Token for api access"
```
which breaks good practice and enterprise governance rules

```
            - gitLabApiTokenImpl:
                scope: GLOBAL
                id: gitlab-cloud-token
                apiToken: "${GITLAB_TOKEN}"
                description: "Gitlab Cloud Token for api access"
```

which is then referenced on the Jenkins resource as 

```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins
spec:
  master:
    containers:
      - name:  jenkins-master
        envFrom:
        - secretRef:
            name: jenkins-gitlab-token
```
