### ISSUE TITLE
Option to use the groovy sandbox for seed jobs pipelines

### ISSUE THREAD

**Issue by tompittson** [jenkinsci/kubernetes-operator#567]
**Describe the solution you'd like**
Currently seed job pipelines are hardcoded to set "Use groovy sandbox" to false. It would be good to include an option to specify whether or not to enable this flag in the Jenkins operator CRD e.g.

```yaml
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
spec:
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
    # New option to configure the groovy sandbox
    useGroovySandbox: true
``` 

**Describe alternatives you've considered**
The value is hardcoded on [seedJobs.go line 109](https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/configuration/user/seedjobs/seedjobs.go#L109). The only options I can see at the moment are to either configure the setting manually after job creation or to create the seed jobs outside of the Jenkins operator definition.

**Additional context**
The goal that this feature request relates to is being able to enable script security for Job DSL scripts as described in [this article](https://www.happycoders.eu/devops/jenkins-tutorial-implementing-seed-job/).
