### ISSUE TITLE
java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.dsl.PodResource.watch

### ISSUE THREAD

**Issue by Schnitzel** [jenkinsci/kubernetes-operator#580]
**Describe the bug**
Jenkins endlessly creates agent pods, filling up the cluster

**To Reproduce**
A jenkins with `kubernetes:1.29.6` and `kubernetes-client-api:5.4.1` installed. This is currently the default: the `kubernetes:1.29.6` is hardcoded in the jenkins operator and `kubernetes-client-api:5.4.1` is installed as it's the newest version of the `kubernetes-client-api` plugin.
After starting a build pod the jenkins job logs look something like this:
```
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Created Pod: kubernetes jenkins/job-6-859cb-9cfg3-8zsfb
Created Pod: kubernetes jenkins/job-6-859cb-9cfg3-951w6
Created Pod: kubernetes jenkins/job-6-859cb-9cfg3-wh5bs
Created Pod: kubernetes jenkins/job-6-859cb-9cfg3-9v9ts
Created Pod: kubernetes jenkins/job-6-859cb-9cfg3-p6zsm
```

this goes endlessly until your kubernetes cluster basically dies because it has multiple thousand of pods running.

In the jenkins logs you can find an error like:
```
java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.dsl.PodResource.watch
```

The issue comes from the fact that `kubernetes:1.29.6` and `kubernetes-client-api:5.4.1` are not compatible with each other.
`kubernetes-client-api:5.4.1`  has breaking api changes: https://plugins.jenkins.io/kubernetes-client-api/#releases
and only `kubernetes:1.30.0` supports them: https://plugins.jenkins.io/kubernetes/#releases

as a workaround until 1.30.0 is installed automatically (https://github.com/jenkinsci/kubernetes-operator/pull/579) you can add this to your helm values:

```
  basePlugins:
    - name: kubernetes
      version: 1.30.0
    - name: workflow-job
      version: '2.41'
    - name: workflow-aggregator
      version: '2.6'
    - name: git
      version: 4.7.2
    - name: job-dsl
      version: '1.77'
    - name: configuration-as-code
      version: '1.51'
    - name: kubernetes-credentials-provider
      version: 0.18-1
```
