### ISSUE TITLE
Host key verification failed - bitbucket seedJob 

### ISSUE THREAD

**Issue by maartengryp** [jenkinsci/kubernetes-operator#588]
I currently experience a ssh problem when trying to connect to bitbucket.org.
I'm installing the jenkins-operator using the latest helm chart version 0.5.1

```
seedJobs:
    - id: my-project
      targets: "jobs/*.jenkins"
      description: "my-project"
      credentialType: basicSSHUserPrivateKey
      credentialID: ssh-bitbucket-key-secret
      repositoryBranch: master
      repositoryUrl: git@bitbucket.org:.../....git
```

Jenkins starts without any problem but my seed job fails with the following exception

```
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --no-tags --force --progress --depth=1 -- git@bitbucket.org:.../....git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Host key verification failed.
fatal: Could not read from remote repository.
```

Any idea on what is going wrong here?
I already tried to mount a known_hosts file into the jenkins pod using a configmap volume, but without success

```
volumes: (pod level)
  - name: ssh-config-volume
    configMap:
      name: ssh-config
      defaultMode: 0600

volumeMounts: (jenkins container)
  - name: ssh-config-volume
    mountPath: "/var/lib/jenkins/.ssh"
```

I cannot find any documented way to specify the known_hosts? What is the advised solution to handle host verification using the jenkins-operator to provision jenkins instances (and dynamic k8s jenkins agents)? 

FYI i'm configured jenkins with the following plugins

```
basePlugins:
      - name: kubernetes
        version: "1.30.0"
      - name: workflow-job
        version: "2.41"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: "4.7.2"
      - name: job-dsl
        version: "1.77"
      - name: configuration-as-code
        version: "1.51"
      - name: kubernetes-credentials-provider
        version: "0.18-1"
      - name: git-client
        version: "3.7.2"
    plugins:
      - name: blueocean
        version: "1.24.7"
      - name: git-parameter
        version: "0.9.13"
      - name: workflow-scm-step
        version: "2.13"
      - name: ssh-agent
        version: "1.23"
```

Thanks!

Update: it worked but after deleting the jenkins and seedjob pod manually. As a result, of course the pods are restarted. Now, the seed job is a success.

My "ssh-bitbucket-key-secret" used in the seedjob is a k8s secret created by akv2k8s (so synced and autogenerated with Azure Keyvault).
Maybe the secret is not available (yet) during the initial startup (have to check, Everything is auto configured using flux - gitops). But if this is the case, i guess the seedJob pod should fail to startup if the secret is unavailable... So probably this is not the cause of the problem...

But my original question remains, how does a jenkins k8s agent handle the host verification?

Update2: Every initial start of the Jenkins seed job still results in stderr: Host key verification failed.
