### ISSUE TITLE
Jenkins pod restart constantly when the plugin version is defined as latest

### ISSUE THREAD

**Issue by ckopparthi** [jenkinsci/kubernetes-operator#615]
**Describe the bug**
Jenkins pod restart constantly when the plugin version is defined as latest.

**To Reproduce**
When defining plugins versions as latest as below Jenkins master pods gets restarted as soon as it spins up.
```
   plugins:
    - name: ldap
      version: "latest"
    - name: simple-theme-plugin
      version: "latest"
    - name: mailer
      version: "latest"
    - name: matrix-auth
      version: "latest".
```
**Additional information**

Kubernetes version:

v1.20.8-gke.2100

Add error logs about the problem here (operator logs and Kubernetes events).
