### ISSUE TITLE
v0.5x Installation plugins are incompatible with backup code

### ISSUE THREAD

**Issue by res0nat0r** [jenkinsci/kubernetes-operator#628]
**Describe the bug**
The base v0.5x installation plugins, listed at the top of the page [here](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/v0.5.x/customization/) are incompatible with the backup and restore code [here](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/v0.5.x/configure-backup-and-restore/)

**To Reproduce**
The base install plugins listed above are:

```yaml
    basePlugins:
    - name: kubernetes
      version: "1.29.2"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.5.0"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.47"
    - name: kubernetes-credentials-provider
      version: "0.15"
```

Booting without any of the `backup:` or `restore:` stanzas works fine and the Jenkins pod will become ready. 
After adding the backup/restore code per the link above, there are plugin incompatibility errors thrown:

```
jenkins-jenkins jenkins-master java.io.IOException: Failed to load: Credentials Plugin (2.5)
jenkins-jenkins jenkins-master  - Update required: Configuration as Code Plugin (1.46) to be updated to 1.51 or higher
jenkins-jenkins jenkins-master 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:950)
jenkins-jenkins jenkins-master 	at hudson.PluginManager$2$1$1.run(PluginManager.java:550)
jenkins-jenkins jenkins-master 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
jenkins-jenkins jenkins-master 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins-jenkins jenkins-master 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
jenkins-jenkins jenkins-master 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins-jenkins jenkins-master 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins-jenkins jenkins-master 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
jenkins-jenkins jenkins-master 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins-jenkins jenkins-master 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins-jenkins jenkins-master 	at java.lang.Thread.run(Thread.java:748)
jenkins-jenkins jenkins-master 2021-08-12 19:06:03.816+0000 [id=29]	SEVERE
```

This appears to be because the base intallation image requires and is using `configuration-as-code:1.46`, but the backup/restore code has hardcoded `configuration-as-code:1.51`, as seen here: https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/plugins/base_plugins.go#L4

Kubernetes version:

Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

Jenkins Operator version:

v0.5x
