### ISSUE TITLE
[v0.6.0] ValidationError(Jenkins.spec): unknown field "validateSecurityWarnings" in Rancher 2.6

### ISSUE THREAD

**Issue by theminer3746** [jenkinsci/kubernetes-operator#684]
**Describe the bug**
Deploying a new operator or upgrading a deployed operator resulted in
`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Jenkins.spec): unknown field "validateSecurityWarnings" in io.jenkins.v1alpha2.Jenkins.spec`

**To Reproduce**
On a Rancher 2.6 cluster (Follow [this](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/aks/) and [this](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/#install-the-rancher-helm-chart) guides to setup Rancher)
1. Add Jenkins K8S operator helm repo via the UI
![image](https://user-images.githubusercontent.com/9322228/146433701-52cb6de8-abb5-4229-aa96-0aad73072f31.png)
2. You should then see jenkins-operator in the Charts page
![image](https://user-images.githubusercontent.com/9322228/146434188-34cea9de-78a3-4fb6-b796-9d8c1903eab6.png)
3. Install jenkins-operator version 0.6.0 via the UI, leaving every settings at the default
![image](https://user-images.githubusercontent.com/9322228/146434872-137d8fab-e235-439d-b585-bfebbbd28b33.png)
4. You should see aforementioned error
![image](https://user-images.githubusercontent.com/9322228/146435193-4a06a615-c0b2-435b-8d01-01342841ad90.png)

**Additional information**

Kubernetes version: 1.20.7
Jenkins Operator version: 0.6.0
Rancher version: 2.6.2 running on Azure Kubernetes Service

1. I followed the guide on [installing the version 0.7 operator](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/). It deployed Jenkins Operator on the cluster without any error but instead of version 0.7.x, the operator version 0.5.3 was deployed.
2. Upgrading the deployed operator from version 0.5.3 to 0.6.x also resulted in the same error.

Add error logs about the problem here (operator logs and Kubernetes events).
Helm command executed by Rancer
```
helm install --namespace=jenkins2 --timeout=10m0s --values=/home/shell/helm/values-jenkins-operator-0.6.0.yaml --version=0.6.0 --wait=true jenkins /home/shell/helm/jenkins-operator-0.6.0.tgz
creating 6 resource(s)
creating 1 resource(s)
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Jenkins.spec): unknown field "validateSecurityWarnings" in io.jenkins.v1alpha2.Jenkins.spec
```

YAML file of jenkins-operator
```
cert-manager:
  startupapicheck:
    enabled: false
jenkins:
  annotations: {}
  apiVersion: jenkins.io/v1alpha2
  authorizationStrategy: createUser
  backup:
    backupCommand:
      - /home/user/bin/backup.sh
    containerName: backup
    enabled: true
    env:
      - name: BACKUP_DIR
        value: /backup
      - name: JENKINS_HOME
        value: /jenkins-home
      - name: BACKUP_COUNT
        value: '3'
    getLatestAction:
      - /home/user/bin/get-latest.sh
    image: virtuslab/jenkins-operator-backup-pvc:v0.1.0
    interval: 30
    makeBackupBeforePodDeletion: true
    pvc:
      className: ''
      enabled: true
      size: 5Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 500Mi
    restoreCommand:
      - /home/user/bin/restore.sh
    volumeMounts:
      - mountPath: /jenkins-home
        name: jenkins-home
      - mountPath: /backup
        name: backup
  basePlugins: []
  configuration:
    configurationAsCode: {}
    groovyScripts: {}
    secretData: {}
    secretRefName: ''
  disableCSRFProtection: false
  enabled: true
  env: []
  image: jenkins/jenkins:2.319.1-lts-alpine
  imagePullPolicy: Always
  imagePullSecrets: []
  labels: {}
  livenessProbe:
    failureThreshold: 20
    httpGet:
      path: /login
      port: http
      scheme: HTTP
    initialDelaySeconds: 100
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 8
  name: jenkins
  namespace: default
  notifications: []
  plugins: []
  priorityClassName: ''
  readinessProbe:
    failureThreshold: 60
    httpGet:
      path: /login
      port: http
      scheme: HTTP
    initialDelaySeconds: 120
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 8
  resources:
    limits:
      cpu: 1000m
      memory: 3Gi
    requests:
      cpu: 1
      memory: 500Mi
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  seedJobs: []
  validateSecurityWarnings: false
  volumeMounts: []
  volumes:
    - name: backup
      persistentVolumeClaim:
        claimName: jenkins-backup
operator:
  affinity: {}
  fullnameOverride: ''
  image: virtuslab/jenkins-operator:v0.7.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  nameOverride: ''
  nodeSelector: {}
  replicaCount: 1
  resources: {}
  tolerations: []
webhook:
  certificate:
    duration: 2160h
    name: webhook-certificate
    renewbefore: 360h
  enabled: false
```
