### ISSUE TITLE
Use on Openshift?

### ISSUE THREAD

**Issue by flickerfly** [jenkinsci/kubernetes-operator#70]
I'm trying to get this running on OpenShift, but am finding the following error in the logs for the operator pod. Is there a way to trigger the operator to run within the allotted range? 

`
2019-08-08T14:59:10.785Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:158	Reconcile loop failed ten times with the same error, giving up: pods "jenkins-jenkins" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000000000, 1000009999] fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000000000, 1000009999]]	{"cr": "jenkins"}
`

If I set a runAsUser like this it moves forward.
```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins
spec:
  master:
    securityContext:
      runAsUser: 1000000500
      runAsGroup: 0
```

EDIT: Setting the runAsUser to an ID within the range 1000000000, 1000009999 works because that is set aside for this project, but we can't make it static (at least for automation purposes) because it will be given a different range in a different project. Each project increments 10k on the previous one.
