### ISSUE TITLE
Incorrect plugin path used when fetching plugins

### ISSUE THREAD

**Issue by leonj1** [jenkinsci/kubernetes-operator#71]
On a new 1.15.2 K8s cluster, and the operator installed, using the following JenkinsInstance manifest the plugin path is incorrect

```
apiVersion: jenkins.jenkinsoperator.samsung-cnct.github.com/v1alpha2
kind: JenkinsInstance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: jenkinsinstance
spec:
  image: "jenkins/jenkins:lts"
  plugins:
    - id: kubernetes
      version: latest
  cascconfig:
    configmap: jenkins-config
  cascsecret: admin-secret
  executors: 1
  adminsecret: admin-secret
  service:
    name: jenkins
    servicetype: ClusterIP
  cascconfig:
      configmap: jenkinsinstance-httpproxy
  cascsecret: jenkins-admin-secret
  storage:
    jobspvc: jenkins
    jobspvcspec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1G
```
The attempted plugin download command is:
```
curl -sSfL --connect-timeout 20 \
--retry 3 --retry-delay 0 --retry-max-time 60 \
https://updates.jenkins.io/2.176/latest/kubernetes-plugin.hpi \
-o /usr/share/jenkins/ref/plugins/kubernetes-plugin.jpi
```
When I run that command manually a 404 is returned
```
curl: (22) The requested URL returned error: 404 Not Found
```
Checking the website where plugins reside, this path is valid (removing the trailing "-plugin"):
```
curl -ksSfL --connect-timeout 20 \
--retry 3 --retry-delay 0 --retry-max-time 60 \
https://updates.jenkins.io/2.176/latest/kubernetes.hpi
# output path redacted for brevity
```

I'm not sure where to change that reference to be able to fetch plugins from a valid path.
Code "getting-started.md" says the init.sh is provided by the operator, but cannot find any init.sh in master branch, or any reference to it, other than the "getting-started.md".
