### ISSUE TITLE
cannot overwrite table with non table for configurationAsCode (map[])

### ISSUE THREAD

**Issue by pasokan-ddn** [jenkinsci/kubernetes-operator#713]
**Unable to enable Jenkins Configuration as Code using helm deployment**

Getting the following error on the deployment, am I messing up with the values input to helm chart or there is a bug using helm to achieve that?

cannot overwrite table with non table for configurationAsCode (map[])

here are my values

```
  configuration:
    #configurationAsCode: {}
    #    - configMapName: jenkins-casc
    #      content: {}
    configurationAsCode:
    - configMapName: jenkins-casc
      content:
        1-system-message.yaml: |
          jenkins:
          systemMessage: "Configuration as Code integration works!!!"
    groovyScripts: {}
    #    - configMapName: jenkins-gs
    #      content: {}

    # secretRefName of existing secret (previously created)
    secretRefName: ""

    # secretData creates new secret if secretRefName is empty and fills with data provided in secretData
    secretData: "default"
```

**To Reproduce**
Steps to reproduce the behavior.

**Additional information**

Kubernetes version: v1.22.0
Jenkins Operator version:v0.7.0

Add error logs about the problem here (operator logs and Kubernetes events).

**Comment by thecooldrop** [comment]
Since your keys contain dots and spaces you need to put them into quotes as follows ( note the quotes areound keys under configMapName.content ):

```yaml
  configuration:
    #configurationAsCode: {}
    #    - configMapName: jenkins-casc
    #      content: {}
    configurationAsCode:
    - configMapName: jenkins-casc
      content:
        "1-system-message.yaml": |
          jenkins:
            systemMessage: "Configuration as Code integration works!!!"
    groovyScripts: {}
    #    - configMapName: jenkins-gs
    #      content: {}

    # secretRefName of existing secret (previously created)
    secretRefName: ""

    # secretData creates new secret if secretRefName is empty and fills with data provided in secretData
    secretData: "default"
```
