### ISSUE TITLE
unable to specify a name of the port in services will be created by Jenkins Operator

### ISSUE THREAD

**Issue by take-a27** [jenkinsci/kubernetes-operator#736]
Currently, Jenkins operator is not allowed to specify the name of port in the service which will be created by Jenkins Operator. I understood from [this page](https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/schema/#github.com/jenkinsci/kubernetes-operator/api/v1alpha2.Service).

So I'd like you to enable to specify the name of port in the service or create the service with named port.
```
  ports:
  -  name: http
     port: 8080
     protocol: TCP
     targetPort: 8080
```

  
The reason is that I'd like to use [this feature](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)  of Istio. Thank you.
