### ISSUE TITLE
Still getting WARN: install-plugins.sh has been removed, please switch to jenkins-plugin-cli

### ISSUE THREAD

**Issue by RichardChester** [jenkinsci/kubernetes-operator#794]
**Describe the bug**
Using image `jenkins/jenkins:2.361.4-lts-alpine`  I still get the error `WARN: install-plugins.sh has been removed, please switch to jenkins-plugin-cli`

**To Reproduce**
Follow steps on the website for installing into kubernetes E.g:
```

apply -f https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/config/crd/bases/jenkins.io_jenkins.yaml 

kubectl apply -f https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/deploy/all-in-one-v1alpha2.yaml
```

Then apply:
```
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: default
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    - name: kubernetes
      version: "1.30.11"
    - name: workflow-job
      version: "1145.v7f2433caa07f"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.10.0"
    - name: job-dsl
      version: "1.78.1"
    - name: configuration-as-code
      version: "1414.v878271fc496f"
    - name: kubernetes-credentials-provider
      version: "0.20"
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.361.4-lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 1000
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 800
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 3000m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 3000Mi
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
```

**Additional information**
I could be mistaken but I thought #791 #764 & #784 were supposed to address this issue #758 has been closed as it should have been complete but I'm still getting the issue

Kubernetes version: 1.25 (minikube)
Jenkins Operator version: 0.71

Add error logs about the problem here (operator logs and Kubernetes events).
```
To print debug messages set environment variable 'DEBUG_JENKINS_OPERATOR' to 'true'
+ '[' '' == true ']'
+ echo 'To print debug messages set environment variable '\''DEBUG_JENKINS_OPERATOR'\'' to '\''true'\'''
+ mkdir -p /var/lib/jenkins/init.groovy.d
+ cp -n /var/jenkins/init-configuration/createOperatorUser.groovy /var/lib/jenkins/init.groovy.d
+ mkdir -p /var/lib/jenkins/scripts
+ cp /var/jenkins/scripts/init.sh /var/jenkins/scripts/install-plugins.sh /var/lib/jenkins/scripts
+ chmod +x /var/lib/jenkins/scripts/init.sh /var/lib/jenkins/scripts/install-plugins.sh
+ echo 'Installing plugins required by Operator - begin'
+ cat
Installing plugins required by Operator - begin
+ [[ -z '' ]]
+ install-plugins.sh
WARN: install-plugins.sh has been removed, please switch to jenkins-plugin-cli
```

**Comment by Harguer** [comment]
hi @RichardChester , could you please paste the output of this command? 
```k get deploy jenkins-operator -o yaml | grep image:```
you should have latest that is image [60b8ee5](https://hub.docker.com/layers/virtuslab/jenkins-operator/60b8ee5/images/sha256-ce7472a2e9dc186d506b08f6fd04d1bc5f228061c3d433ba5d7308d2dc4ef097?context=explore) , this one has the changes :)

**Comment by RichardChester** [comment]
Hello @Harguer 
```
$ kubectl get deploy jenkins-operator -o yaml | grep image:
        image: virtuslab/jenkins-operator:v0.7.1
```

**Comment by RichardChester** [comment]
Hay so changing it to 
`image: virtuslab/jenkins-operator:60b8ee5`
made the whole thing work, but I still don't get why the links I got from the website downloaded the wrong one operator

**Comment by RichardChester** [comment]
That being said now I'm past the plugins-cli error I got to bash: line `1: /usr/bin/tini: No such file or directory` which I thought had also been fixed in #764 . I must be using the right image in the operator though or I wouldn't have gotten that far ?

**Comment by Harguer** [comment]
I have tested your configuration, just modified the namespace and the name of the cr and seems breaking on plugins
```
kind: Jenkins
metadata:
  name: jenkins
  namespace: jenkins2
```
after fixed the plugins (as per the logs showed up in the jenkins master container), here is the list of valid plugins you can use:
```
    basePlugins:
    - name: kubernetes
      version: "3802.vb_b_600831fcb_3"
    - name: workflow-job
      version: "1189.va_d37a_e9e4eda_"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.10.0"
    - name: job-dsl
      version: "1.78.1"
    - name: configuration-as-code
      version: "1569.vb_72405b_80249"
    - name: kubernetes-credentials-provider
      version: "1.208.v128ee9800c04"
```

I also got the error you described, but it is with the lts image you are using, i tried with this and worked fine `2.375.2-lts`
