### ISSUE TITLE
Project status updates and roadmap

### ISSUE THREAD

**Issue by brokenpip3** [jenkinsci/kubernetes-operator#802]
Hi community! :wave: 

As you may notice I stepped up  to try to maintain this project from the previous maintainers.
I'm happy :rocket:  about this new role and I will try to do my best to keep this project rolling :) 

I want to share with the community what I think should be our new roadmap in order to gather comments, feedbacks and suggestions. 

**Current situation**
Right now the operator is still alive and working against the latest jenkins lts version due to the PRs I made in the past weeks but the overall health is not great, we need to fix some basic stuff (see below) before moving forward and start adding new features.

**Future**
This is what I thought: (happy to receive any feedback) we should plan 3 new major releases:

* v0.8 PR: https://github.com/jenkinsci/kubernetes-operator/pull/806
This version should be shipped as soon will be possible since the latest release it's ~1y old and should contains:
   * make the operator works against the latest jenkins lts version :heavy_check_mark: 
   * Migrate from dockerhub to quay.io :heavy_check_mark: 
   * Fix the repo CI with less makefile dependencies, add the backup ones etc :heavy_check_mark: 
   * Add more tests :heavy_check_mark: 
   * the remaining `0.8` issues: https://github.com/jenkinsci/kubernetes-operator/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.8

* v0.9
This version will be the foundation for the future versions and will contains:
   * Update to the latest operator-sdk version (if possible)
   * Update the go version since we are using `1.15` atm
   * Publish the helm chart directly in the operator site, also avoid to store the helm chart artifacts in the git repo.
   * Enhance operator/jenkins security
   * Fix docs and add more around plugins and configuration
   * the remaining `0.9` issues: https://github.com/jenkinsci/kubernetes-operator/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.9
   
* v0.10
Finally this will be the version where we can start to add new features starting from some outstanding issues that we have in the repo: https://github.com/jenkinsci/kubernetes-operator/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.10

**Community**
We are looking for new contributors/maintainers, any help we can get from the community will be great and will help the project to move faster! :rocket: 
Also we need a new "community" place to discuss, right now we have 2 options: 
* start using the jenkins discourse https://community.jenkins.io/c/contributing/jenkins-operator/20 
* find a new slack home :heavy_check_mark: 

Like I said any suggestions, criticism and support will be appreciated :bow:

**Comment by rkrzewski** [comment]
@brokenpip3, thank you so much for stepping up as the maintainer!

For those that are struggling to keep their v0.7.1 operator instance running, and are willing to do a bit of pre-release testing, here's a snippet of my `values.yaml` with important settings that allowed me to start an up-to-date LTS Jenkins today:
```
operator:
  image: quay.io/jenkins-kubernetes-operator/operator:d91a729
jenkins:
  image: jenkins/jenkins:2.387.1-lts
  basePlugins:
   - name: kubernetes
     version: 3883.v4d70a_a_a_df034
   - name: workflow-job
     version: 1284.v2fe8ed4573d4
   - name: workflow-aggregator
     version: 596.v8c21c963d92d
   - name: git
     version: 5.0.0
   - name: job-dsl
     version: "1.81"
   - name: configuration-as-code
     version: 1569.vb_72405b_80249
   - name: kubernetes-credentials-provider
     version: 1.209.v862c6e5fb_1ef
```
The plugin versions are correct as of today, see #797
