### ISSUE TITLE
JCASC Merge of lists from different files is not working.

### ISSUE THREAD

**Issue by lhupfeldt** [jenkinsci/kubernetes-operator#898]
We are having an issue with casc files not being merged the same way they are on a non kubernetes/operator setup.

Given the following configmap (unrelated parts removed):
```
apiVersion: v1
data:
  1-jcasc-pipeline-library.yml: |
    ---
    unclassified:
      globalLibraries:
        libraries:
        - defaultVersion: "main"
          includeInChangesets: false
          name: pipeline-library-1"
          retriever:
            modernSCM:
              scm:
                github:
                  configuredByUrl: true
                  credentialsId: "stdc.github.userpass"
                  repoOwner: "devops"
                  repository: "pipeline-library-1"
                  repositoryUrl: "https://somewhere/devops/pipeline-library-1.git"
                  traits:
                  - gitHubBranchDiscovery:
                      strategyId: 1
                  - gitHubPullRequestDiscovery:
                      strategyId: 1
                  - gitHubForkDiscovery:
                      strategyId: 1
                      trust: "gitHubTrustPermissions"
  2-jcasc-pipeline-library.yml: |
    ---
    unclassified:
      globalLibraries:
        libraries:
        - defaultVersion: "main"
          includeInChangesets: false
          name: pipeline-library-2"
          retriever:
            modernSCM:
              scm:
                github:
                  configuredByUrl: true
                  credentialsId: "stdc.github.userpass"
                  repoOwner: "devops"
                  repository: "pipeline-library-2"
                  repositoryUrl: "https://somewhere/devops/pipeline-library-2.git"
                  traits:
                  - gitHubBranchDiscovery:
                      strategyId: 1
                  - gitHubPullRequestDiscovery:
                      strategyId: 1
                  - gitHubForkDiscovery:
                      strategyId: 1
                      trust: "gitHubTrustPermissions"    
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jenkins-operator-user-configuration
```

What we see is:
Only a single library is defined in Jenkins.
The second library casc file overwrites the first one. 
There are no errors logged from the casc file processing.

Kubernetes version: v1.24.15+rke2r1
Jenkins Operator version: v0.8.0-beta2

With the lirary definitions in separate casc files on non-kubernete Jenkins both libraries will be defined.
I.e. The (one element) list in the second file is appended to the list from the first file.

Can you explain how the casc processing is done with the operator?
I see that the log output is in the operator log, not the Jenkins log as I would have expected. 
I would have expected that the configmap files were mounted in the Jenkins container, but that does not seem to be the case.
