### ISSUE TITLE
Unable to reference an existing Jenkins CR in a different namespace

### ISSUE THREAD

**Issue by valenca** [jenkinsci/kubernetes-operator#922]
**Describe the bug**
When setting the jenkins.enabled configuration to false (i.e. telling the operator to look at an existing Jenkins CR, as opposed to creating a new one from the values), we can no longer set the namespace, as it will read the operator's metadata to compute the Jenkins namespace.

**To Reproduce**
Create a Jenkins CR in namespace "jenkins"
Install the jenkins operator in the namespace operators, with jenkins.enabled = false and jenkins.namespace = jenkins. It will not be able to find the Jenkins CR in the jenkins ns, and will idle waiting for one in the operator namespace.

**Additional information**
It was introduced by this commit, specifically:
https://github.com/jenkinsci/kubernetes-operator/commit/1b6e944ae63b4c2ec9bc915cb2627f3442d0f90d

Kubernetes version:
Jenkins Operator version:
0.8.0

Workaround:
Since we are deploying the operator with kustomize, we can do a post-render step to change the WATCH_NAMESPACE operator env var:

```
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
        - kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: jenkins-jenkins-operator
          spec:
            template:
              spec:
                containers:
                  - name: jenkins-operator
                    env:
                      - name: WATCH_NAMESPACE
                        $patch: delete
        - kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: jenkins-jenkins-operator
          spec:
            template:
              spec:
                containers:
                  - name: jenkins-operator
                    env:
                      - name: WATCH_NAMESPACE
                        value: jenkins
```

It's always possible to change the deployment directly, but as far as we tried, it wasn't possible to do it within the values.yaml file.
